const LANGUAGE_OPTIONS = [
  { code: 'en', label: 'EN' },
  { code: 'ru', label: 'RU' },
  { code: 'ko', label: 'KO' },
  { code: 'de', label: 'DE' },
  { code: 'fr', label: 'FR' },
  { code: 'es', label: 'ES' },
  { code: 'it', label: 'IT' },
  { code: 'ja', label: 'JA' },
  { code: 'zh', label: 'ZH' }
];
const SUPPORTED_LANGS = LANGUAGE_OPTIONS.map((item) => item.code);
const DEFAULT_LANG = 'en';
const STORAGE_KEY = 'dojo4education_lang';

const t = {
  en: {
    meta: {
      indexTitle: 'Dojo4Education — AI tools for education',
      indexDescription: 'AI-powered mini-apps and training tools for academic preparation, oral answers, and skill development.',
      thesisTitle: 'ThesisAudit — AI oral defense trainer',
      thesisDescription: 'ThesisAudit helps students rehearse oral academic defense with AI-generated questions, voice answers, and structured feedback.',
      lingvoTitle: 'LingvoScenes — AI language lessons from real context',
      lingvoDescription: 'LingvoScenes helps create polished language-learning video lessons from permitted materials, with clear explanations and practice support.'
    },
    common: {
      products: 'Products',
      about: 'About',
      contact: 'Contact',
      soon: 'soon',
      thesisAudit: 'ThesisAudit',
      lingvoScenes: 'LingvoScenes',
      lingvaPulse: 'LingvaPulse',
      footer: '© 2026 Dojo4Education · Powered by AI',
      telegram: 'Telegram community'
    },
    index: {
      eyebrow: 'AI tools for education',
      title: 'Practice skills with <span class="accent">AI-powered trainers</span>',
      subtitle: 'Dojo4Education develops compact AI mini-apps that help learners prepare, explain, answer, and improve practical academic skills.',
      ctaProducts: 'Explore products',
      ctaThesis: 'View ThesisAudit',
      visualTitle: 'Mini-apps and training tools for skill development',
      productsLabel: '// products',
      productsTitle: 'Focused tools instead of generic AI chats',
      thesisDesc: 'AI trainer for thesis defense and oral academic preparation. It generates questions, accepts voice answers, analyzes reasoning, and is available on Google Play.',
      lingvoDesc: 'AI desktop app for creating polished language-learning lessons from permitted video materials.',
      lingvaDesc: 'AI tools for language learning: smart drills, speech analysis, and personalized progress tracking.',
      available: 'available',
      privateRollout: 'private rollout',
      aboutLabel: '// business profile',
      aboutTitle: 'Small software business, focused on education technology',
      aboutText: 'Dojo4Education is a registered software development project in South Korea. The goal is to build practical AI tools for students, learners, and educators — starting with oral preparation and skill training.',
      businessName: '<strong>Business name:</strong> Dojo4Education',
      businessNameKr: '<strong>Registered Korean name:</strong> 도조포에듀케이션',
      businessType: '<strong>Business type:</strong> Software development',
      businessFocus: '<strong>Focus:</strong> AI tools for education and skill development',
      roadmapTitle: 'Roadmap',
      roadmapText: 'The current focus is ThesisAudit. LingvaPulse and additional learning tools are planned as the product line expands.',
      contactLabel: '// contact',
      contactTitle: 'Business inquiries and product updates',
      contactText: 'For business communication, partnership inquiries, or product questions, use email. Community updates are available through Telegram.',
      emailButton: 'Contact by email',
      telegramButton: 'Open Telegram'
    },
    thesis: {
      eyebrow: 'AI oral defense trainer',
      title: 'Knowing is one thing.<br><span class="grad">Explaining it aloud is another.</span>',
      lead: 'ThesisAudit simulates an academic defense: it asks questions based on your document, accepts voice answers, and shows where your reasoning becomes weak before it happens in front of a committee.',
      insight: 'A text may feel clear while reading. But when you try to answer aloud, gaps appear in <strong>logic, terminology, and argumentation</strong>. ThesisAudit helps find them early.',
      download: 'Get it on Google Play',
      androidNote: 'Android app available on Google Play',
      useLabel: '// use cases',
      useTitle: 'One tool for multiple oral formats',
      uc1Name: 'Thesis defense',
      uc1Desc: 'The main scenario. Questions about topic, methodology, conclusions, and practical value — similar to a real committee.',
      uc1Badge: 'main scenario',
      uc2Name: 'Course paper',
      uc2Desc: 'Practice answers about the research topic, structure, conclusions, and source selection.',
      uc3Name: 'Lab report',
      uc3Desc: 'Check whether you can explain not only the practical part, but also the theory behind it.',
      uc4Name: 'Essay or report',
      uc4Desc: 'Rehearse topic explanation, argumentation, and answers to follow-up questions from a teacher.',
      uc5Name: 'Seminars',
      uc5Desc: 'Test readiness to discuss class topics and participate with clear arguments.',
      uc6Name: 'Exams and oral tests',
      uc6Desc: 'Model questions from learning materials and train oral answers under realistic pressure.',
      stepsLabel: '// how it works',
      stepsTitle: 'A structured rehearsal, not just random questions',
      step1Title: 'Upload your material',
      step1Desc: 'Thesis, course paper, report, lecture notes, textbook chapters — any preparation document in .docx format.',
      step2Title: 'Receive questions',
      step2Desc: 'AI analyzes the material and generates questions about the topic, methodology, conclusions, practical value, and key terms.',
      step3Title: 'Answer by voice',
      step3Desc: 'Answer aloud as you would during a real defense. Voice answers are transcribed and analyzed.',
      step4Title: 'Follow-up questions',
      step4Desc: 'Based on your answers, the system asks additional questions to test depth of understanding and argument logic.',
      step5Title: 'Get the final report',
      step5Desc: 'A detailed report with readiness level, strengths, weak points, and specific areas to improve before the real defense.',
      valueLabel: '// value',
      valueTitle: 'A safe space for real rehearsal',
      value1Title: 'Find weak points early',
      value1Text: 'Detect gaps in understanding before the real conversation with a teacher or committee.',
      value2Title: 'Train oral answers',
      value2Text: 'Practice explaining aloud — a different skill than simply knowing the material.',
      value3Title: 'Build argumentation',
      value3Text: 'Improve the logic of explanation, the connection between theory and practice, and the justification of conclusions.',
      value4Title: 'Reduce stress',
      value4Text: 'When you have already rehearsed a similar situation, the real defense feels less unknown.',
      creditsLabel: '// credits and access',
      creditsTitle: 'Start for free',
      credit1Val: '20',
      credit1Text: 'free Dojocoins after authorization',
      credit2Val: '1,000',
      credit2Text: 'words per 1 Dojocoin, rounded up',
      credit3Val: 'Google Play',
      credit3Text: 'Android app distribution channel',
      notice: 'Dojocoins are used to measure document processing volume. The current free start gives 20 Dojocoins, and 1 Dojocoin covers 1,000 words with rounding up.'
    },
    lingvo: {
      eyebrow: 'AI language-learning video lessons',
      title: 'Learn languages through<br><span class="grad">scenes that feel real.</span>',
      lead: 'LingvoScenes helps turn permitted video materials into polished language-learning lessons for personal study, teachers, and creators. The focus is simple: context, explanation, and repeatable practice in one viewing experience.',
      insight: 'Learners do not just memorize isolated phrases. They see <strong>meaning, situation, tone, and explanation</strong> together, so real speech becomes easier to notice and remember.',
      contactButton: 'Request access',
      overviewButton: 'See overview',
      rolloutNote: 'Windows desktop app in private rollout',
      useLabel: '// use cases',
      useTitle: 'Language lessons built around real context',
      uc1Name: 'Scene-based lessons',
      uc1Desc: 'Create compact lessons around meaningful moments from permitted learning materials.',
      uc1Badge: 'main scenario',
      uc2Name: 'Dialogue understanding',
      uc2Desc: 'Help learners follow how meaning develops across a conversation, not just a single phrase.',
      uc3Name: 'Clear explanations',
      uc3Desc: 'Present vocabulary, grammar, tone, and cultural context in a learner-friendly way.',
      uc4Name: 'Creator-ready lessons',
      uc4Desc: 'Prepare polished educational videos for private study, classes, or public learning channels.',
      uc5Name: 'Study materials',
      uc5Desc: 'Support lessons with summaries, vocabulary focus, and exercises for review.',
      uc6Name: 'Responsible use',
      uc6Desc: 'Designed for educational work with materials the user has the right to use.',
      stepsLabel: '// lesson experience',
      stepsTitle: 'What learners get from a LingvoScenes lesson',
      step1Title: 'Natural context',
      step1Desc: 'Language appears inside a situation, with emotion and intent visible.',
      step2Title: 'Focused learning moments',
      step2Desc: 'Lessons highlight useful expressions without making the experience feel like a dictionary.',
      step3Title: 'Plain explanations',
      step3Desc: 'Learners get concise explanations of meaning, grammar, tone, and usage.',
      step4Title: 'Watch-and-repeat format',
      step4Desc: 'The finished lesson is made for repeated viewing, classroom use, and self-study.',
      step5Title: 'Optional study support',
      step5Desc: 'Lessons can be paired with review materials, vocabulary notes, and exercises.',
      valueLabel: '// value',
      valueTitle: 'Built for teachers, creators, and serious learners',
      value1Title: 'Context-rich learning',
      value1Text: 'Scenes keep natural speed, emotion, and situation visible while explanations make the language approachable.',
      value2Title: 'Multiple learning languages',
      value2Text: 'Designed for learners working with English, German, French, Italian, Spanish, Korean, Chinese, and Japanese.',
      value3Title: 'Polished lesson output',
      value3Text: 'The final material is designed to feel like a finished educational product, not a rough draft.',
      value4Title: 'Responsible publishing',
      value4Text: 'Clear positioning helps creators think carefully about where and how educational materials are used.',
      accessLabel: '// editions and access',
      accessTitle: 'Private rollout now, wider access later',
      access1Val: 'Trial',
      access1Text: 'limited evaluation access for trying the product',
      access2Val: 'Home',
      access2Text: 'desktop edition for personal lesson creation',
      access3Val: 'Pro',
      access3Text: 'planned edition for advanced creators and educators',
      notice: 'LingvoScenes is designed for educational use with materials the user is allowed to process. Publishing rules and copyright requirements depend on the source material and platform.'
    }
  },
  ru: {
    meta: {
      indexTitle: 'Dojo4Education — AI-инструменты для образования',
      indexDescription: 'AI-мини-приложения и тренажёры для академической подготовки, устных ответов и развития навыков.',
      thesisTitle: 'ThesisAudit — AI-тренажёр устной подготовки',
      thesisDescription: 'ThesisAudit помогает репетировать устную защиту с AI-вопросами, голосовыми ответами и структурированной обратной связью.',
      lingvoTitle: 'LingvoScenes — AI-уроки языка в живом контексте',
      lingvoDescription: 'LingvoScenes помогает создавать аккуратные видеоуроки языка из разрешённых материалов: с понятными объяснениями и поддержкой практики.'
    },
    common: {
      products: 'Продукты',
      about: 'О проекте',
      contact: 'Контакты',
      soon: 'скоро',
      thesisAudit: 'ThesisAudit',
      lingvoScenes: 'LingvoScenes',
      lingvaPulse: 'LingvaPulse',
      footer: '© 2026 Dojo4Education · Powered by AI',
      telegram: 'Telegram-сообщество'
    },
    index: {
      eyebrow: 'AI-инструменты для образования',
      title: 'Развивайте навыки с помощью <span class="accent">AI-тренажёров</span>',
      subtitle: 'Dojo4Education создаёт компактные AI-мини-приложения, которые помогают учиться, готовиться, объяснять вслух и развивать практические академические навыки.',
      ctaProducts: 'Смотреть продукты',
      ctaThesis: 'Открыть ThesisAudit',
      visualTitle: 'Мини-приложения и тренажёры для развития навыков',
      productsLabel: '// продукты',
      productsTitle: 'Фокусные инструменты вместо универсальных AI-чатов',
      thesisDesc: 'AI-тренажёр защиты диплома и устной академической подготовки. Генерирует вопросы, принимает голосовые ответы, анализирует аргументацию и доступен в Google Play.',
      lingvoDesc: 'AI-приложение для создания аккуратных видеоуроков языка из разрешённых видеоматериалов.',
      lingvaDesc: 'AI-инструменты для изучения языков: умные тренировки, анализ речи и персональный прогресс.',
      available: 'доступно',
      privateRollout: 'закрытый доступ',
      aboutLabel: '// бизнес-профиль',
      aboutTitle: 'Небольшой software-бизнес с фокусом на EdTech',
      aboutText: 'Dojo4Education — зарегистрированный в Южной Корее проект по разработке программного обеспечения. Цель — создавать практические AI-инструменты для студентов, учащихся и преподавателей, начиная с устной подготовки и тренировки навыков.',
      businessName: '<strong>Название бизнеса:</strong> Dojo4Education',
      businessNameKr: '<strong>Зарегистрированное корейское название:</strong> 도조포에듀케이션',
      businessType: '<strong>Вид деятельности:</strong> разработка программного обеспечения',
      businessFocus: '<strong>Фокус:</strong> AI-инструменты для образования и развития навыков',
      roadmapTitle: 'Дорожная карта',
      roadmapText: 'Текущий фокус — ThesisAudit. LingvaPulse и дополнительные учебные инструменты планируются по мере развития продуктовой линейки.',
      contactLabel: '// контакты',
      contactTitle: 'Деловые запросы и новости продукта',
      contactText: 'Для деловой коммуникации, партнёрских вопросов и вопросов по продукту используйте email. Обновления сообщества доступны через Telegram.',
      emailButton: 'Написать по email',
      telegramButton: 'Открыть Telegram'
    },
    thesis: {
      eyebrow: 'AI-тренажёр устной подготовки',
      title: 'Знать — это одно.<br><span class="grad">Объяснить вслух — другое.</span>',
      lead: 'ThesisAudit моделирует академическую защиту: задаёт вопросы по вашему документу, принимает голосовые ответы и показывает, где аргументация слабеет — до того, как это произойдёт перед комиссией.',
      insight: 'Материал может казаться понятным при чтении. Но при попытке ответить вслух обнаруживаются пробелы в <strong>логике, терминологии и аргументации</strong>. ThesisAudit помогает найти их заранее.',
      download: 'Открыть в Google Play',
      androidNote: 'Android-приложение доступно в Google Play',
      useLabel: '// сценарии использования',
      useTitle: 'Один инструмент для разных устных форматов',
      uc1Name: 'Защита диплома',
      uc1Desc: 'Главный сценарий. Вопросы по теме, методологии, выводам и практической значимости — как от настоящей комиссии.',
      uc1Badge: 'основной сценарий',
      uc2Name: 'Курсовая работа',
      uc2Desc: 'Отработайте ответы по теме исследования, структуре работы, обоснованию выводов и выбранным источникам.',
      uc3Name: 'Лабораторная работа',
      uc3Desc: 'Проверьте, способны ли вы объяснить не только практическую часть, но и лежащую в основе теорию.',
      uc4Name: 'Реферат или доклад',
      uc4Desc: 'Репетиция изложения темы, аргументации и ответов на уточняющие вопросы преподавателя.',
      uc5Name: 'Семинары',
      uc5Desc: 'Проверьте готовность к обсуждению тем и аргументированному участию в занятии.',
      uc6Name: 'Зачёты и экзамены',
      uc6Desc: 'Моделирование вопросов по учебным материалам и тренировка устных ответов в реалистичных условиях.',
      stepsLabel: '// как это работает',
      stepsTitle: 'Структурированная репетиция, а не просто набор вопросов',
      step1Title: 'Загружаете материал',
      step1Desc: 'Диплом, курсовая, реферат, конспекты лекций, главы учебника — любой документ для подготовки в формате .docx.',
      step2Title: 'Получаете вопросы',
      step2Desc: 'AI анализирует материал и формирует вопросы по теме, методологии, выводам, практической значимости и ключевым понятиям.',
      step3Title: 'Отвечаете голосом',
      step3Desc: 'Отвечаете устно — как на реальной защите. Голосовые ответы транскрибируются и анализируются системой.',
      step4Title: 'Уточняющие вопросы',
      step4Desc: 'На основе ваших ответов система задаёт дополнительные вопросы, проверяя глубину понимания и логику аргументации.',
      step5Title: 'Получаете итоговый отчёт',
      step5Desc: 'Детальный отчёт: уровень готовности, сильные и слабые стороны, конкретные зоны для доработки перед реальной защитой.',
      valueLabel: '// ценность',
      valueTitle: 'Безопасная среда для настоящей репетиции',
      value1Title: 'Видите слабые места заранее',
      value1Text: 'Находите пробелы в понимании до реального разговора с преподавателем или комиссией.',
      value2Title: 'Тренируете устный ответ',
      value2Text: 'Учитесь объяснять вслух — это другой навык, чем просто знать материал.',
      value3Title: 'Выстраиваете аргументацию',
      value3Text: 'Прорабатываете логику изложения, связь теории с практикой и обоснование выводов.',
      value4Title: 'Снижаете стресс',
      value4Text: 'Когда вы уже репетировали похожую ситуацию, реальная защита перестаёт быть неизвестностью.',
      creditsLabel: '// кредиты и доступ',
      creditsTitle: 'Начните бесплатно',
      credit1Val: '20',
      credit1Text: 'бесплатных Dojocoins после авторизации',
      credit2Val: '1 000',
      credit2Text: 'слов на 1 Dojocoin, с округлением вверх',
      credit3Val: 'Google Play',
      credit3Text: 'канал распространения Android-приложения',
      notice: 'Dojocoins используются для измерения объёма обработки документов. Сейчас при старте выдаётся 20 Dojocoins, а 1 Dojocoin покрывает 1 000 слов с округлением вверх.'
    },
    lingvo: {
      eyebrow: 'AI-видеоуроки для изучения языков',
      title: 'Учите языки через<br><span class="grad">сцены, которые ощущаются живыми.</span>',
      lead: 'LingvoScenes помогает превращать разрешённые видеоматериалы в аккуратные уроки языка для самостоятельного обучения, преподавателей и авторов. Фокус простой: контекст, объяснение и повторяемая практика в одном формате просмотра.',
      insight: 'Учащийся не просто запоминает отдельные фразы. Он видит <strong>смысл, ситуацию, тон и объяснение</strong> вместе, поэтому живую речь проще замечать и запоминать.',
      contactButton: 'Запросить доступ',
      overviewButton: 'Посмотреть обзор',
      rolloutNote: 'Windows-приложение в закрытом доступе',
      useLabel: '// сценарии',
      useTitle: 'Уроки языка, построенные вокруг живого контекста',
      uc1Name: 'Уроки на основе сцен',
      uc1Desc: 'Создавайте компактные уроки вокруг значимых моментов из разрешённых учебных материалов.',
      uc1Badge: 'главный сценарий',
      uc2Name: 'Понимание диалога',
      uc2Desc: 'Помогайте учащимся видеть, как смысл развивается в разговоре, а не только в одной фразе.',
      uc3Name: 'Понятные объяснения',
      uc3Desc: 'Показывайте лексику, грамматику, тон и культурный контекст в удобном для учащегося виде.',
      uc4Name: 'Уроки для авторов',
      uc4Desc: 'Готовьте аккуратные образовательные видео для личного обучения, занятий или публичных учебных каналов.',
      uc5Name: 'Учебные материалы',
      uc5Desc: 'Дополняйте уроки краткими конспектами, словарным фокусом и упражнениями для повторения.',
      uc6Name: 'Ответственное использование',
      uc6Desc: 'Продукт рассчитан на образовательную работу с материалами, которые пользователь имеет право использовать.',
      stepsLabel: '// учебный опыт',
      stepsTitle: 'Что получает учащийся в уроке LingvoScenes',
      step1Title: 'Живой контекст',
      step1Desc: 'Язык появляется внутри ситуации, где видны эмоция и намерение.',
      step2Title: 'Сфокусированные учебные моменты',
      step2Desc: 'Уроки выделяют полезные выражения, не превращая просмотр в словарь.',
      step3Title: 'Простые объяснения',
      step3Desc: 'Учащийся получает краткие пояснения смысла, грамматики, тона и употребления.',
      step4Title: 'Формат для повторения',
      step4Desc: 'Готовый урок подходит для повторного просмотра, занятий и самостоятельного обучения.',
      step5Title: 'Дополнительная поддержка',
      step5Desc: 'Уроки можно дополнять материалами для повторения, словарными заметками и упражнениями.',
      valueLabel: '// ценность',
      valueTitle: 'Для преподавателей, авторов и серьёзных учащихся',
      value1Title: 'Контекстное обучение',
      value1Text: 'Сцены сохраняют естественную скорость, эмоцию и ситуацию, а объяснения делают язык доступнее.',
      value2Title: 'Несколько языков изучения',
      value2Text: 'Подходит для учащихся, которые работают с английским, немецким, французским, итальянским, испанским, корейским, китайским и японским.',
      value3Title: 'Аккуратный учебный результат',
      value3Text: 'Итоговый материал задуман как готовый образовательный продукт, а не сырой фрагмент.',
      value4Title: 'Ответственная публикация',
      value4Text: 'Чёткое позиционирование помогает авторам заранее думать, где и как используются учебные материалы.',
      accessLabel: '// версии и доступ',
      accessTitle: 'Сейчас закрытый доступ, позже шире',
      access1Val: 'Trial',
      access1Text: 'ограниченный доступ для знакомства с продуктом',
      access2Val: 'Home',
      access2Text: 'desktop-версия для личного создания уроков',
      access3Val: 'Pro',
      access3Text: 'планируемая версия для авторов и преподавателей',
      notice: 'LingvoScenes предназначен для образовательного использования с материалами, которые пользователь имеет право обрабатывать. Правила публикации и требования авторского права зависят от исходного материала и платформы.'
    }
  },
  ko: {
    meta: {
      indexTitle: 'Dojo4Education — 교육용 AI 도구',
      indexDescription: '학업 준비, 구두 답변, 기술 개발을 위한 AI 기반 미니 앱과 트레이닝 도구입니다.',
      thesisTitle: 'ThesisAudit — AI 구두 발표 훈련 도구',
      thesisDescription: 'ThesisAudit은 AI 질문, 음성 답변, 구조화된 피드백으로 학업 발표와 논문 방어를 연습하도록 돕습니다.',
      lingvoTitle: 'LingvoScenes — 실제 맥락 기반 AI 언어 수업',
      lingvoDescription: 'LingvoScenes는 사용이 허용된 자료로부터 명확한 설명과 연습 지원이 있는 완성도 높은 언어 학습 비디오 수업을 만들도록 돕습니다.'
    },
    common: {
      products: '제품',
      about: '소개',
      contact: '문의',
      soon: '준비 중',
      thesisAudit: 'ThesisAudit',
      lingvoScenes: 'LingvoScenes',
      lingvaPulse: 'LingvaPulse',
      footer: '© 2026 Dojo4Education · Powered by AI',
      telegram: 'Telegram 커뮤니티'
    },
    index: {
      eyebrow: '교육용 AI 도구',
      title: '<span class="accent">AI 훈련 도구</span>로 학습 역량을 연습하세요',
      subtitle: 'Dojo4Education은 학습자가 준비하고, 설명하고, 답변하며, 실질적인 학업 역량을 발전시킬 수 있도록 돕는 AI 미니 앱을 개발합니다.',
      ctaProducts: '제품 보기',
      ctaThesis: 'ThesisAudit 보기',
      visualTitle: '역량 개발을 위한 미니 앱과 훈련 도구',
      productsLabel: '// 제품',
      productsTitle: '일반 AI 채팅이 아닌 목적 중심 도구',
      thesisDesc: '논문 방어와 구두 학업 준비를 위한 AI 훈련 도구입니다. 질문을 생성하고, 음성 답변을 받으며, 논리 전개를 분석하고 Google Play에서 이용할 수 있습니다.',
      lingvoDesc: '사용이 허용된 비디오 자료로 완성도 높은 언어 학습 수업을 만드는 AI 데스크톱 앱입니다.',
      lingvaDesc: '언어 학습을 위한 AI 도구입니다. 스마트 훈련, 발화 분석, 개인별 진행 상황 추적을 제공합니다.',
      available: '사용 가능',
      privateRollout: '비공개 배포',
      aboutLabel: '// 비즈니스 프로필',
      aboutTitle: '교육 기술에 집중하는 소규모 소프트웨어 비즈니스',
      aboutText: 'Dojo4Education은 한국에 등록된 소프트웨어 개발 프로젝트입니다. 학생, 학습자, 교육자를 위한 실용적인 AI 도구를 만드는 것을 목표로 하며, 구두 준비와 역량 훈련부터 시작합니다.',
      businessName: '<strong>비즈니스명:</strong> Dojo4Education',
      businessNameKr: '<strong>한국 등록 상호:</strong> 도조포에듀케이션',
      businessType: '<strong>업종:</strong> 소프트웨어 개발',
      businessFocus: '<strong>분야:</strong> 교육 및 역량 개발을 위한 AI 도구',
      roadmapTitle: '로드맵',
      roadmapText: '현재 초점은 ThesisAudit입니다. 제품 라인이 확장되면서 LingvaPulse와 추가 학습 도구가 계획되어 있습니다.',
      contactLabel: '// 문의',
      contactTitle: '비즈니스 문의 및 제품 업데이트',
      contactText: '비즈니스 커뮤니케이션, 파트너십 문의 또는 제품 관련 질문은 이메일을 이용해 주세요. 커뮤니티 업데이트는 Telegram에서 확인할 수 있습니다.',
      emailButton: '이메일 문의',
      telegramButton: 'Telegram 열기'
    },
    thesis: {
      eyebrow: 'AI 구두 발표 훈련 도구',
      title: '아는 것과<br><span class="grad">소리 내어 설명하는 것은 다릅니다.</span>',
      lead: 'ThesisAudit은 학업 발표 상황을 시뮬레이션합니다. 문서를 기반으로 질문을 생성하고, 음성 답변을 받으며, 실제 심사 전에 논리의 약점을 보여줍니다.',
      insight: '글로 읽을 때는 명확해 보이는 내용도, 소리 내어 답하려고 하면 <strong>논리, 용어, 논증</strong>의 빈틈이 드러납니다. ThesisAudit은 이를 미리 찾도록 돕습니다.',
      download: 'Google Play에서 열기',
      androidNote: 'Android 앱은 Google Play에서 이용 가능합니다',
      useLabel: '// 활용 사례',
      useTitle: '여러 구두 평가 형식에 사용할 수 있는 도구',
      uc1Name: '논문 방어',
      uc1Desc: '주요 시나리오입니다. 주제, 방법론, 결론, 실무적 가치에 대한 질문을 실제 위원회처럼 연습합니다.',
      uc1Badge: '주요 시나리오',
      uc2Name: '과제 보고서',
      uc2Desc: '연구 주제, 구성, 결론, 참고 자료 선택에 대한 답변을 연습합니다.',
      uc3Name: '실험 보고서',
      uc3Desc: '실습 내용뿐 아니라 그 기반이 되는 이론까지 설명할 수 있는지 확인합니다.',
      uc4Name: '리포트 또는 발표',
      uc4Desc: '주제 설명, 논증, 교사의 추가 질문에 대한 답변을 연습합니다.',
      uc5Name: '세미나',
      uc5Desc: '수업 주제에 대해 토론하고 명확한 근거로 참여할 준비가 되었는지 확인합니다.',
      uc6Name: '시험 및 구두 평가',
      uc6Desc: '학습 자료 기반 질문을 만들고 실제 상황에 가까운 압박 속에서 구두 답변을 훈련합니다.',
      stepsLabel: '// 작동 방식',
      stepsTitle: '무작위 질문이 아닌 구조화된 리허설',
      step1Title: '자료 업로드',
      step1Desc: '논문, 과제, 보고서, 강의 노트, 교재 장 등 .docx 형식의 준비 자료를 업로드합니다.',
      step2Title: '질문 받기',
      step2Desc: 'AI가 자료를 분석해 주제, 방법론, 결론, 실무적 가치, 핵심 용어에 대한 질문을 생성합니다.',
      step3Title: '음성으로 답변',
      step3Desc: '실제 발표처럼 소리 내어 답변합니다. 음성 답변은 텍스트로 변환되고 분석됩니다.',
      step4Title: '추가 질문',
      step4Desc: '답변을 바탕으로 시스템이 추가 질문을 제시해 이해 깊이와 논리 전개를 점검합니다.',
      step5Title: '최종 보고서 받기',
      step5Desc: '준비 수준, 강점, 약점, 실제 발표 전 개선해야 할 구체적인 영역을 담은 상세 보고서를 받습니다.',
      valueLabel: '// 가치',
      valueTitle: '실전 리허설을 위한 안전한 환경',
      value1Title: '약점을 미리 발견',
      value1Text: '교사나 위원회와의 실제 대화 전에 이해의 빈틈을 찾습니다.',
      value2Title: '구두 답변 훈련',
      value2Text: '소리 내어 설명하는 연습을 합니다. 이는 단순히 아는 것과는 다른 능력입니다.',
      value3Title: '논리 구성 강화',
      value3Text: '설명의 흐름, 이론과 실제의 연결, 결론의 근거를 개선합니다.',
      value4Title: '스트레스 감소',
      value4Text: '비슷한 상황을 이미 연습했다면 실제 발표는 덜 낯설게 느껴집니다.',
      creditsLabel: '// 크레딧 및 이용 조건',
      creditsTitle: '무료로 시작하세요',
      credit1Val: '20',
      credit1Text: '인증 후 무료 Dojocoins',
      credit2Val: '1,000',
      credit2Text: '1 Dojocoin당 단어 수, 올림 처리',
      credit3Val: 'Google Play',
      credit3Text: 'Android 앱 배포 채널',
      notice: 'Dojocoins는 문서 처리량을 측정하는 데 사용됩니다. 현재 시작 시 20 Dojocoins가 무료로 제공되며, 1 Dojocoin은 1,000단어를 올림 처리하여 사용할 수 있습니다.'
    },
    lingvo: {
      eyebrow: 'AI 언어 학습 비디오 수업',
      title: '실감 나는 장면으로<br><span class="grad">언어를 배우세요.</span>',
      lead: 'LingvoScenes는 사용이 허용된 비디오 자료를 개인 학습자, 교사, 크리에이터를 위한 완성도 높은 언어 학습 수업으로 만드는 데 도움을 줍니다. 핵심은 한 번의 시청 경험 안에 맥락, 설명, 반복 연습을 담는 것입니다.',
      insight: '학습자는 고립된 문장만 외우지 않습니다. <strong>의미, 상황, 말투, 설명</strong>을 함께 보며 실제 표현을 더 쉽게 알아차리고 기억합니다.',
      contactButton: '접근 요청',
      overviewButton: '개요 보기',
      rolloutNote: 'Windows 데스크톱 앱 비공개 배포 중',
      useLabel: '// 활용 사례',
      useTitle: '실제 맥락을 중심으로 한 언어 수업',
      uc1Name: '장면 기반 수업',
      uc1Desc: '사용이 허용된 학습 자료의 의미 있는 순간을 중심으로 짧고 집중된 수업을 만듭니다.',
      uc1Badge: '주요 시나리오',
      uc2Name: '대화 이해',
      uc2Desc: '학습자가 한 문장만이 아니라 대화 속에서 의미가 어떻게 전개되는지 따라가도록 돕습니다.',
      uc3Name: '명확한 설명',
      uc3Desc: '어휘, 문법, 말투, 문화적 맥락을 학습자에게 친절한 방식으로 보여줍니다.',
      uc4Name: '크리에이터용 수업',
      uc4Desc: '개인 학습, 수업, 공개 학습 채널에 어울리는 완성도 높은 교육 영상을 준비합니다.',
      uc5Name: '학습 자료',
      uc5Desc: '요약, 어휘 포인트, 복습용 연습 문제로 수업을 보완합니다.',
      uc6Name: '책임 있는 사용',
      uc6Desc: '사용자가 사용할 권리가 있는 자료를 바탕으로 한 교육 작업을 위해 설계되었습니다.',
      stepsLabel: '// 학습 경험',
      stepsTitle: 'LingvoScenes 수업에서 학습자가 얻는 것',
      step1Title: '자연스러운 맥락',
      step1Desc: '언어가 감정과 의도가 보이는 상황 안에서 제시됩니다.',
      step2Title: '집중된 학습 순간',
      step2Desc: '수업은 유용한 표현을 강조하면서도 사전처럼 느껴지지 않게 합니다.',
      step3Title: '쉬운 설명',
      step3Desc: '의미, 문법, 말투, 사용법에 대한 간결한 설명을 제공합니다.',
      step4Title: '반복 시청 형식',
      step4Desc: '완성된 수업은 반복 시청, 수업 활용, 자기주도 학습에 맞게 구성됩니다.',
      step5Title: '추가 학습 지원',
      step5Desc: '복습 자료, 어휘 노트, 연습 문제와 함께 사용할 수 있습니다.',
      valueLabel: '// 가치',
      valueTitle: '교사, 크리에이터, 진지한 학습자를 위해',
      value1Title: '맥락이 있는 학습',
      value1Text: '장면은 자연스러운 속도, 감정, 상황을 유지하고 설명은 언어를 더 접근 가능하게 만듭니다.',
      value2Title: '여러 학습 언어',
      value2Text: '영어, 독일어, 프랑스어, 이탈리아어, 스페인어, 한국어, 중국어, 일본어를 공부하는 학습자를 위해 설계되었습니다.',
      value3Title: '완성도 높은 수업 결과물',
      value3Text: '최종 자료는 원본 조각이 아니라 완성된 교육 콘텐츠처럼 느껴지도록 설계됩니다.',
      value4Title: '책임 있는 공개',
      value4Text: '명확한 방향성은 크리에이터가 교육 자료를 어디서 어떻게 사용할지 신중히 판단하도록 돕습니다.',
      accessLabel: '// 버전과 접근',
      accessTitle: '현재는 비공개 배포, 이후 확대 예정',
      access1Val: 'Trial',
      access1Text: '제품을 체험하기 위한 제한 평가 접근',
      access2Val: 'Home',
      access2Text: '개인 수업 제작을 위한 데스크톱 버전',
      access3Val: 'Pro',
      access3Text: '고급 크리에이터와 교육자를 위한 예정 버전',
      notice: 'LingvoScenes는 사용자가 처리할 권한이 있는 자료를 교육 목적으로 활용하도록 설계되었습니다. 게시 규칙과 저작권 요구사항은 원본 자료와 플랫폼에 따라 달라집니다.'
    }
  },
  it: {
    meta: {
      indexTitle: 'Dojo4Education — strumenti IA per l’educazione',
      indexDescription: 'Mini-app e strumenti di allenamento con IA per preparazione accademica, risposte orali e sviluppo delle competenze.',
      thesisTitle: 'ThesisAudit — trainer IA per discussioni orali',
      thesisDescription: 'ThesisAudit aiuta gli studenti a provare discussioni accademiche con domande IA, risposte vocali e feedback strutturato.',
      lingvoTitle: 'LingvoScenes — lezioni IA di lingua da contesti reali',
      lingvoDescription: 'LingvoScenes aiuta a creare videolezioni di lingua curate da materiali consentiti, con spiegazioni chiare e supporto alla pratica.'
    },
    common: {
      products: 'Prodotti',
      about: 'Chi siamo',
      contact: 'Contatti',
      soon: 'presto',
      thesisAudit: 'ThesisAudit',
      lingvoScenes: 'LingvoScenes',
      lingvaPulse: 'LingvaPulse',
      footer: '© 2026 Dojo4Education · Powered by AI',
      telegram: 'Community Telegram'
    },
    index: {
      eyebrow: 'Strumenti IA per l’educazione',
      title: 'Allena le competenze con <span class="accent">trainer basati su IA</span>',
      subtitle: 'Dojo4Education sviluppa mini-app IA compatte che aiutano a preparare, spiegare, rispondere e migliorare competenze accademiche pratiche.',
      ctaProducts: 'Esplora i prodotti',
      ctaThesis: 'Vedi ThesisAudit',
      visualTitle: 'Mini-app e strumenti di allenamento per sviluppare competenze',
      productsLabel: '// prodotti',
      productsTitle: 'Strumenti mirati invece di chat IA generiche',
      thesisDesc: 'Trainer IA per discussione di tesi e preparazione orale accademica. Genera domande, accetta risposte vocali, analizza il ragionamento ed è disponibile su Google Play.',
      lingvoDesc: 'App desktop IA per creare lezioni di lingua curate da materiali video consentiti.',
      lingvaDesc: 'Strumenti IA per apprendere lingue: esercizi intelligenti, analisi del parlato e progresso personalizzato.',
      available: 'disponibile',
      privateRollout: 'accesso privato',
      aboutLabel: '// profilo',
      aboutTitle: 'Piccola impresa software focalizzata su tecnologia educativa',
      aboutText: 'Dojo4Education è un progetto di sviluppo software registrato in Corea del Sud. L’obiettivo è creare strumenti IA pratici per studenti, apprendenti e docenti, iniziando dalla preparazione orale.',
      businessName: '<strong>Nome commerciale:</strong> Dojo4Education',
      businessNameKr: '<strong>Nome coreano registrato:</strong> 도조포에듀케이션',
      businessType: '<strong>Attività:</strong> sviluppo software',
      businessFocus: '<strong>Focus:</strong> strumenti IA per educazione e competenze',
      roadmapTitle: 'Roadmap',
      roadmapText: 'Il focus attuale è ThesisAudit. LingvaPulse e altri strumenti di apprendimento sono pianificati con l’espansione della linea prodotti.',
      contactLabel: '// contatti',
      contactTitle: 'Richieste business e aggiornamenti prodotto',
      contactText: 'Per comunicazioni commerciali, partnership o domande sui prodotti, usa l’e-mail. Gli aggiornamenti della community sono disponibili su Telegram.',
      emailButton: 'Contatta via e-mail',
      telegramButton: 'Apri Telegram'
    },
    thesis: {
      eyebrow: 'Trainer IA per discussioni orali',
      title: 'Sapere è una cosa.<br><span class="grad">Spiegarlo ad alta voce è un’altra.</span>',
      lead: 'ThesisAudit simula una discussione accademica: pone domande sul tuo documento, accetta risposte vocali e mostra dove il ragionamento si indebolisce prima della commissione reale.',
      insight: 'Un testo può sembrare chiaro durante la lettura. Ma quando rispondi ad alta voce emergono lacune in <strong>logica, terminologia e argomentazione</strong>. ThesisAudit aiuta a trovarle presto.',
      download: 'Scarica da Google Play',
      androidNote: 'App Android disponibile su Google Play',
      useLabel: '// casi d’uso',
      useTitle: 'Uno strumento per diversi formati orali',
      uc1Name: 'Discussione di tesi',
      uc1Desc: 'Lo scenario principale. Domande su tema, metodologia, conclusioni e valore pratico, come in una vera commissione.',
      uc1Badge: 'scenario principale',
      uc2Name: 'Tesina o lavoro di corso',
      uc2Desc: 'Esercitati su tema di ricerca, struttura, conclusioni e scelta delle fonti.',
      uc3Name: 'Relazione di laboratorio',
      uc3Desc: 'Verifica se sai spiegare non solo la parte pratica, ma anche la teoria alla base.',
      uc4Name: 'Saggio o relazione',
      uc4Desc: 'Prova spiegazione del tema, argomentazione e risposte a domande di approfondimento.',
      uc5Name: 'Seminari',
      uc5Desc: 'Controlla la tua prontezza nel discutere temi del corso con argomenti chiari.',
      uc6Name: 'Esami orali',
      uc6Desc: 'Modella domande dai materiali di studio e allena risposte orali sotto pressione realistica.',
      stepsLabel: '// come funziona',
      stepsTitle: 'Una prova strutturata, non solo domande casuali',
      step1Title: 'Carica il materiale',
      step1Desc: 'Tesi, tesina, relazione, appunti o capitoli di manuale: qualsiasi documento di preparazione in formato .docx.',
      step2Title: 'Ricevi domande',
      step2Desc: 'L’IA analizza il materiale e genera domande su tema, metodologia, conclusioni, valore pratico e termini chiave.',
      step3Title: 'Rispondi con la voce',
      step3Desc: 'Rispondi ad alta voce come in una vera discussione. Le risposte vocali vengono trascritte e analizzate.',
      step4Title: 'Domande di approfondimento',
      step4Desc: 'In base alle risposte, il sistema pone altre domande per testare profondità e logica argomentativa.',
      step5Title: 'Ottieni il report finale',
      step5Desc: 'Un report dettagliato con livello di preparazione, punti forti, punti deboli e aree concrete da migliorare.',
      valueLabel: '// valore',
      valueTitle: 'Uno spazio sicuro per una vera prova',
      value1Title: 'Trova presto i punti deboli',
      value1Text: 'Individua lacune di comprensione prima del vero confronto con docente o commissione.',
      value2Title: 'Allena le risposte orali',
      value2Text: 'Esercitati a spiegare ad alta voce: è una competenza diversa dal semplice sapere.',
      value3Title: 'Costruisci argomentazione',
      value3Text: 'Migliora logica della spiegazione, collegamento tra teoria e pratica e giustificazione delle conclusioni.',
      value4Title: 'Riduci lo stress',
      value4Text: 'Quando hai già provato una situazione simile, la discussione reale sembra meno sconosciuta.',
      creditsLabel: '// crediti e accesso',
      creditsTitle: 'Inizia gratis',
      credit1Val: '20',
      credit1Text: 'Dojocoins gratuiti dopo autorizzazione',
      credit2Val: '1.000',
      credit2Text: 'parole per 1 Dojocoin, arrotondate per eccesso',
      credit3Val: 'Google Play',
      credit3Text: 'canale di distribuzione Android',
      notice: 'I Dojocoins misurano il volume di elaborazione dei documenti. L’avvio gratuito attuale offre 20 Dojocoins, e 1 Dojocoin copre 1.000 parole con arrotondamento.'
    },
    lingvo: {
      eyebrow: 'Videolezioni IA per imparare lingue',
      title: 'Impara le lingue attraverso<br><span class="grad">scene che sembrano reali.</span>',
      lead: 'LingvoScenes aiuta a trasformare materiali video consentiti in lezioni di lingua curate per studio personale, insegnanti e creator. Il focus è semplice: contesto, spiegazione e pratica ripetibile in un’unica esperienza.',
      insight: 'Chi studia non memorizza solo frasi isolate. Vede insieme <strong>significato, situazione, tono e spiegazione</strong>, così il parlato reale diventa più facile da notare e ricordare.',
      contactButton: 'Richiedi accesso',
      overviewButton: 'Vedi panoramica',
      rolloutNote: 'App Windows in accesso privato',
      useLabel: '// casi d’uso',
      useTitle: 'Lezioni di lingua costruite intorno a contesti reali',
      uc1Name: 'Lezioni basate su scene',
      uc1Desc: 'Crea lezioni compatte intorno a momenti significativi da materiali di apprendimento consentiti.',
      uc1Badge: 'scenario principale',
      uc2Name: 'Comprensione del dialogo',
      uc2Desc: 'Aiuta a seguire come il significato si sviluppa in una conversazione, non solo in una singola frase.',
      uc3Name: 'Spiegazioni chiare',
      uc3Desc: 'Presenta vocabolario, grammatica, tono e contesto culturale in modo adatto allo studente.',
      uc4Name: 'Lezioni pronte per creator',
      uc4Desc: 'Prepara video educativi curati per studio personale, lezioni o canali pubblici di apprendimento.',
      uc5Name: 'Materiali di studio',
      uc5Desc: 'Supporta le lezioni con riassunti, focus sul vocabolario ed esercizi di ripasso.',
      uc6Name: 'Uso responsabile',
      uc6Desc: 'Pensato per lavoro educativo con materiali che l’utente ha il diritto di usare.',
      stepsLabel: '// esperienza di apprendimento',
      stepsTitle: 'Cosa offre una lezione LingvoScenes',
      step1Title: 'Contesto naturale',
      step1Desc: 'La lingua appare dentro una situazione, con emozione e intenzione visibili.',
      step2Title: 'Momenti di apprendimento mirati',
      step2Desc: 'Le lezioni evidenziano espressioni utili senza sembrare un dizionario.',
      step3Title: 'Spiegazioni semplici',
      step3Desc: 'Chi studia riceve spiegazioni concise di significato, grammatica, tono e uso.',
      step4Title: 'Formato guarda e ripeti',
      step4Desc: 'La lezione finita è pensata per rivedere, usare in classe e studiare da soli.',
      step5Title: 'Supporto di studio opzionale',
      step5Desc: 'Le lezioni possono essere accompagnate da materiali di ripasso, note lessicali ed esercizi.',
      valueLabel: '// valore',
      valueTitle: 'Per docenti, creator e studenti seri',
      value1Title: 'Apprendimento con contesto',
      value1Text: 'Le scene mantengono velocità naturale, emozione e situazione, mentre le spiegazioni rendono la lingua accessibile.',
      value2Title: 'Più lingue di studio',
      value2Text: 'Pensato per chi studia inglese, tedesco, francese, italiano, spagnolo, coreano, cinese e giapponese.',
      value3Title: 'Risultato didattico curato',
      value3Text: 'Il materiale finale è pensato per sembrare un prodotto educativo finito, non un frammento grezzo.',
      value4Title: 'Pubblicazione responsabile',
      value4Text: 'Una comunicazione chiara aiuta i creator a pensare con attenzione a dove e come usare i materiali educativi.',
      accessLabel: '// edizioni e accesso',
      accessTitle: 'Ora accesso privato, poi disponibilità più ampia',
      access1Val: 'Trial',
      access1Text: 'accesso di valutazione limitato per provare il prodotto',
      access2Val: 'Home',
      access2Text: 'edizione desktop per creare lezioni personali',
      access3Val: 'Pro',
      access3Text: 'edizione prevista per creator avanzati e docenti',
      notice: 'LingvoScenes è pensato per uso educativo con materiali che l’utente è autorizzato a elaborare. Regole di pubblicazione e copyright dipendono dal materiale e dalla piattaforma.'
    }
  },
  ja: {
    meta: {
      indexTitle: 'Dojo4Education — 教育向けAIツール',
      indexDescription: '学術準備、口頭回答、スキル向上のためのAIミニアプリとトレーニングツールです。',
      thesisTitle: 'ThesisAudit — 口頭発表のためのAIトレーナー',
      thesisDescription: 'ThesisAuditは、AI質問、音声回答、構造化されたフィードバックで学術発表の練習を支援します。',
      lingvoTitle: 'LingvoScenes — 実際の文脈から作るAI語学レッスン',
      lingvoDescription: 'LingvoScenesは、利用が許可された素材から、明確な解説と練習サポートを備えた語学動画レッスンを作る支援をします。'
    },
    common: {
      products: 'プロダクト',
      about: '概要',
      contact: 'お問い合わせ',
      soon: '近日公開',
      thesisAudit: 'ThesisAudit',
      lingvoScenes: 'LingvoScenes',
      lingvaPulse: 'LingvaPulse',
      footer: '© 2026 Dojo4Education · Powered by AI',
      telegram: 'Telegramコミュニティ'
    },
    index: {
      eyebrow: '教育向けAIツール',
      title: '<span class="accent">AIトレーナー</span>で実践的なスキルを鍛える',
      subtitle: 'Dojo4Educationは、学習者が準備し、説明し、答え、実践的な学術スキルを伸ばすための小さなAIミニアプリを開発しています。',
      ctaProducts: 'プロダクトを見る',
      ctaThesis: 'ThesisAuditを見る',
      visualTitle: 'スキル向上のためのミニアプリとトレーニングツール',
      productsLabel: '// プロダクト',
      productsTitle: '汎用AIチャットではなく、目的に集中したツール',
      thesisDesc: '卒業論文の口頭試問や学術発表準備のためのAIトレーナー。質問を生成し、音声回答を受け取り、論理を分析します。Google Playで利用できます。',
      lingvoDesc: '利用が許可された動画素材から、完成度の高い語学レッスンを作るAIデスクトップアプリです。',
      lingvaDesc: '語学学習向けAIツール：スマート練習、音声分析、個別の進捗管理。',
      available: '利用可能',
      privateRollout: '限定公開',
      aboutLabel: '// 事業概要',
      aboutTitle: '教育テクノロジーに集中する小規模ソフトウェア事業',
      aboutText: 'Dojo4Educationは韓国で登録されたソフトウェア開発プロジェクトです。学生、学習者、教育者のための実用的なAIツールを作ることを目指し、まず口頭準備とスキルトレーニングから始めています。',
      businessName: '<strong>事業名:</strong> Dojo4Education',
      businessNameKr: '<strong>登録韓国名:</strong> 도조포에듀케이션',
      businessType: '<strong>事業種別:</strong> ソフトウェア開発',
      businessFocus: '<strong>重点領域:</strong> 教育とスキル開発のためのAIツール',
      roadmapTitle: 'ロードマップ',
      roadmapText: '現在の中心はThesisAuditです。LingvaPulseと追加の学習ツールは、製品ラインの拡大に合わせて計画されています。',
      contactLabel: '// お問い合わせ',
      contactTitle: '事業相談とプロダクト更新',
      contactText: '事業連絡、提携、製品に関する質問はメールをご利用ください。コミュニティ更新はTelegramで確認できます。',
      emailButton: 'メールで連絡',
      telegramButton: 'Telegramを開く'
    },
    thesis: {
      eyebrow: '口頭発表のためのAIトレーナー',
      title: '知っていることと、<br><span class="grad">声に出して説明できることは違います。</span>',
      lead: 'ThesisAuditは学術発表をシミュレーションします。文書に基づいて質問し、音声回答を受け取り、本番の委員会の前に論理が弱くなる箇所を示します。',
      insight: '文章は読んでいると明確に感じられます。しかし声に出して答えると、<strong>論理、用語、主張</strong>の穴が見えてきます。ThesisAuditはそれを早めに見つけます。',
      download: 'Google Playで入手',
      androidNote: 'AndroidアプリはGoogle Playで利用可能',
      useLabel: '// 利用シーン',
      useTitle: '複数の口頭形式に対応する一つのツール',
      uc1Name: '論文審査',
      uc1Desc: '主なシナリオ。テーマ、方法論、結論、実用的価値について、実際の委員会に近い質問を行います。',
      uc1Badge: '主なシナリオ',
      uc2Name: 'レポート・課題',
      uc2Desc: '研究テーマ、構成、結論、資料選択についての回答を練習します。',
      uc3Name: '実験レポート',
      uc3Desc: '実践部分だけでなく、その背後にある理論も説明できるか確認します。',
      uc4Name: 'エッセイ・発表',
      uc4Desc: 'テーマ説明、主張、教師からの追加質問への回答を練習します。',
      uc5Name: 'ゼミ',
      uc5Desc: '授業テーマを議論し、明確な根拠で参加できるか確認します。',
      uc6Name: '試験・口頭テスト',
      uc6Desc: '学習資料から質問をモデル化し、現実的な緊張感の中で口頭回答を訓練します。',
      stepsLabel: '// 仕組み',
      stepsTitle: 'ただのランダム質問ではなく、構造化されたリハーサル',
      step1Title: '資料をアップロード',
      step1Desc: '論文、レポート、講義ノート、教科書の章など、.docx形式の準備資料を使用できます。',
      step2Title: '質問を受け取る',
      step2Desc: 'AIが資料を分析し、テーマ、方法論、結論、実用的価値、重要語句について質問を生成します。',
      step3Title: '声で回答する',
      step3Desc: '本番の発表のように声に出して答えます。音声回答は文字起こしされ、分析されます。',
      step4Title: '追加質問',
      step4Desc: '回答に基づき、理解の深さと論理の流れを確認する追加質問を行います。',
      step5Title: '最終レポートを受け取る',
      step5Desc: '準備度、強み、弱点、本番前に改善すべき具体的な領域を含む詳細レポートです。',
      valueLabel: '// 価値',
      valueTitle: '本番に近い練習のための安全な場所',
      value1Title: '弱点を早く見つける',
      value1Text: '教師や委員会との本番の会話の前に、理解の穴を検出します。',
      value2Title: '口頭回答を鍛える',
      value2Text: '声に出して説明する練習をします。これは単に知っていることとは別のスキルです。',
      value3Title: '主張を組み立てる',
      value3Text: '説明の論理、理論と実践のつながり、結論の根拠を改善します。',
      value4Title: '緊張を減らす',
      value4Text: '似た状況をすでに練習していれば、本番の発表は未知のものではなくなります。',
      creditsLabel: '// クレジットとアクセス',
      creditsTitle: '無料で開始',
      credit1Val: '20',
      credit1Text: '認証後の無料Dojocoins',
      credit2Val: '1,000',
      credit2Text: '1 Dojocoinあたりの単語数、切り上げ',
      credit3Val: 'Google Play',
      credit3Text: 'Androidアプリの配布チャネル',
      notice: 'Dojocoinsは文書処理量を測るために使用されます。現在の無料開始では20 Dojocoinsが付与され、1 Dojocoinは1,000語までを切り上げでカバーします。'
    },
    lingvo: {
      eyebrow: '語学学習のためのAI動画レッスン',
      title: 'リアルに感じられる場面で<br><span class="grad">言語を学ぶ。</span>',
      lead: 'LingvoScenesは、利用が許可された動画素材を、個人学習、教師、クリエイター向けの完成度の高い語学レッスンにする支援をします。大切なのは、文脈、解説、くり返し練習を一つの視聴体験にまとめることです。',
      insight: '学習者は孤立したフレーズを暗記するだけではありません。<strong>意味、状況、トーン、解説</strong>を一緒に見ることで、実際の表現に気づき、記憶しやすくなります。',
      contactButton: 'アクセスをリクエスト',
      overviewButton: '概要を見る',
      rolloutNote: 'Windowsデスクトップアプリ、限定公開中',
      useLabel: '// 利用シーン',
      useTitle: '実際の文脈を中心にした語学レッスン',
      uc1Name: '場面ベースのレッスン',
      uc1Desc: '利用が許可された学習素材の意味ある瞬間を中心に、短く集中したレッスンを作ります。',
      uc1Badge: '主なシナリオ',
      uc2Name: '会話理解',
      uc2Desc: '一つの文だけでなく、会話の中で意味がどう展開するかを追えるようにします。',
      uc3Name: 'わかりやすい解説',
      uc3Desc: '語彙、文法、トーン、文化的文脈を学習者にやさしい形で示します。',
      uc4Name: 'クリエイター向けレッスン',
      uc4Desc: '個人学習、授業、公開学習チャンネルに使える整った教育動画を準備します。',
      uc5Name: '学習教材',
      uc5Desc: '要約、語彙ポイント、復習用の練習問題でレッスンを補助します。',
      uc6Name: '責任ある利用',
      uc6Desc: 'ユーザーが使用する権利を持つ素材を使った教育活動のために設計されています。',
      stepsLabel: '// 学習体験',
      stepsTitle: 'LingvoScenesのレッスンで学習者が得るもの',
      step1Title: '自然な文脈',
      step1Desc: '言語が、感情と意図の見える状況の中で提示されます。',
      step2Title: '集中した学習ポイント',
      step2Desc: 'レッスンは役立つ表現を強調しながら、辞書のような体験にはしません。',
      step3Title: 'シンプルな解説',
      step3Desc: '意味、文法、トーン、使い方を簡潔に説明します。',
      step4Title: '見てくり返す形式',
      step4Desc: '完成したレッスンは、くり返し視聴、授業利用、自習に向いています。',
      step5Title: '追加の学習サポート',
      step5Desc: '復習素材、語彙メモ、練習問題と組み合わせられます。',
      valueLabel: '// 価値',
      valueTitle: '教師、クリエイター、本気の学習者のために',
      value1Title: '文脈のある学習',
      value1Text: 'シーンは自然な速度、感情、状況を保ち、解説が言語を理解しやすくします。',
      value2Title: '複数の学習言語',
      value2Text: '英語、ドイツ語、フランス語、イタリア語、スペイン語、韓国語、中国語、日本語を学ぶ人向けに設計されています。',
      value3Title: '整った教育コンテンツ',
      value3Text: '最終素材は、生の断片ではなく完成した教育プロダクトのように感じられることを目指しています。',
      value4Title: '責任ある公開',
      value4Text: '明確な位置づけにより、クリエイターが教育素材をどこでどう使うか慎重に考えられます。',
      accessLabel: '// エディションとアクセス',
      accessTitle: '現在は限定公開、今後さらに拡大',
      access1Val: 'Trial',
      access1Text: 'ワークフロー確認用の制限付き評価版',
      access2Val: 'Home',
      access2Text: '個人レッスン作成向けデスクトップ版',
      access3Val: 'Pro',
      access3Text: '上級クリエイターと教育者向けに計画中の版',
      notice: 'LingvoScenesは、ユーザーが処理する権利を持つ素材を教育目的で利用するために設計されています。公開ルールと著作権要件は素材とプラットフォームによって異なります。'
    }
  },
  zh: {
    meta: {
      indexTitle: 'Dojo4Education — 教育 AI 工具',
      indexDescription: '用于学术准备、口头回答和能力提升的 AI 小应用与训练工具。',
      thesisTitle: 'ThesisAudit — 口头答辩 AI 训练器',
      thesisDescription: 'ThesisAudit 通过 AI 提问、语音回答和结构化反馈，帮助学生练习学术口头答辩。',
      lingvoTitle: 'LingvoScenes — 来自真实语境的 AI 语言课程',
      lingvoDescription: 'LingvoScenes 帮助从允许使用的材料创建精致的语言学习视频课程，并提供清晰讲解和练习支持。'
    },
    common: {
      products: '产品',
      about: '关于',
      contact: '联系',
      soon: '即将推出',
      thesisAudit: 'ThesisAudit',
      lingvoScenes: 'LingvoScenes',
      lingvaPulse: 'LingvaPulse',
      footer: '© 2026 Dojo4Education · Powered by AI',
      telegram: 'Telegram 社群'
    },
    index: {
      eyebrow: '教育 AI 工具',
      title: '用 <span class="accent">AI 训练器</span> 提升真实技能',
      subtitle: 'Dojo4Education 开发紧凑的 AI 小应用，帮助学习者准备、解释、回答并提升实用的学术能力。',
      ctaProducts: '查看产品',
      ctaThesis: '查看 ThesisAudit',
      visualTitle: '用于能力提升的小应用和训练工具',
      productsLabel: '// 产品',
      productsTitle: '专注工具，而不是泛泛的 AI 聊天',
      thesisDesc: '用于论文答辩和学术口头准备的 AI 训练器。它生成问题、接收语音回答、分析论证，并已在 Google Play 提供。',
      lingvoDesc: 'AI 桌面应用，用于从允许使用的视频材料创建精致的语言学习课程。',
      lingvaDesc: '语言学习 AI 工具：智能练习、语音分析和个性化进度跟踪。',
      available: '可用',
      privateRollout: '私密测试',
      aboutLabel: '// 业务资料',
      aboutTitle: '专注教育科技的小型软件业务',
      aboutText: 'Dojo4Education 是在韩国注册的软件开发项目。目标是为学生、学习者和教师构建实用 AI 工具，从口头准备和技能训练开始。',
      businessName: '<strong>业务名称:</strong> Dojo4Education',
      businessNameKr: '<strong>注册韩文名称:</strong> 도조포에듀케이션',
      businessType: '<strong>业务类型:</strong> 软件开发',
      businessFocus: '<strong>重点:</strong> 教育和能力发展的 AI 工具',
      roadmapTitle: '路线图',
      roadmapText: '当前重点是 ThesisAudit。随着产品线扩展，LingvaPulse 和更多学习工具将陆续规划。',
      contactLabel: '// 联系',
      contactTitle: '商务咨询和产品更新',
      contactText: '商务沟通、合作咨询或产品问题请使用电子邮件。社群更新可通过 Telegram 获取。',
      emailButton: '通过邮件联系',
      telegramButton: '打开 Telegram'
    },
    thesis: {
      eyebrow: '口头答辩 AI 训练器',
      title: '知道是一回事。<br><span class="grad">能大声讲清楚是另一回事。</span>',
      lead: 'ThesisAudit 模拟学术答辩：根据你的文档提出问题，接收语音回答，并在真正面对委员会之前指出论证变弱的地方。',
      insight: '文字在阅读时可能显得清楚。但当你开口回答时，<strong>逻辑、术语和论证</strong>中的空缺会暴露出来。ThesisAudit 帮你提前发现它们。',
      download: '在 Google Play 获取',
      androidNote: 'Android 应用已在 Google Play 提供',
      useLabel: '// 使用场景',
      useTitle: '适用于多种口头形式的一款工具',
      uc1Name: '论文答辩',
      uc1Desc: '核心场景。围绕主题、方法、结论和实际价值提问，接近真实委员会的形式。',
      uc1Badge: '核心场景',
      uc2Name: '课程论文',
      uc2Desc: '练习关于研究主题、结构、结论和资料选择的回答。',
      uc3Name: '实验报告',
      uc3Desc: '检查你是否不仅能解释实践部分，也能解释背后的理论。',
      uc4Name: '论文或报告',
      uc4Desc: '练习主题说明、论证以及回答教师追问。',
      uc5Name: '研讨课',
      uc5Desc: '测试自己是否能讨论课堂主题，并用清晰论据参与交流。',
      uc6Name: '考试和口试',
      uc6Desc: '根据学习材料生成问题，在接近真实压力的环境下训练口头回答。',
      stepsLabel: '// 工作方式',
      stepsTitle: '结构化演练，而不是随机提问',
      step1Title: '上传材料',
      step1Desc: '论文、课程作业、报告、讲义、教材章节等，任何 .docx 格式的准备文档。',
      step2Title: '获得问题',
      step2Desc: 'AI 分析材料，并围绕主题、方法、结论、实际价值和关键术语生成问题。',
      step3Title: '用语音回答',
      step3Desc: '像真实答辩一样大声回答。语音回答会被转写并分析。',
      step4Title: '追问',
      step4Desc: '系统会根据你的回答继续提问，以测试理解深度和论证逻辑。',
      step5Title: '获得最终报告',
      step5Desc: '详细报告包含准备程度、优势、薄弱点以及真实答辩前需要改进的具体方向。',
      valueLabel: '// 价值',
      valueTitle: '用于真实演练的安全空间',
      value1Title: '提前发现弱点',
      value1Text: '在真正与老师或委员会交流之前发现理解上的空缺。',
      value2Title: '训练口头回答',
      value2Text: '练习大声解释。这与只是知道材料是不同的能力。',
      value3Title: '建立论证',
      value3Text: '改善解释逻辑、理论与实践的连接，以及结论的依据。',
      value4Title: '降低压力',
      value4Text: '如果你已经演练过相似场景，真正的答辩就不会那么陌生。',
      creditsLabel: '// 积分和访问',
      creditsTitle: '免费开始',
      credit1Val: '20',
      credit1Text: '授权后的免费 Dojocoins',
      credit2Val: '1,000',
      credit2Text: '每 1 Dojocoin 覆盖的词数，向上取整',
      credit3Val: 'Google Play',
      credit3Text: 'Android 应用分发渠道',
      notice: 'Dojocoins 用于衡量文档处理量。当前免费开始提供 20 个 Dojocoins，1 个 Dojocoin 覆盖 1,000 个词并向上取整。'
    },
    lingvo: {
      eyebrow: '用于语言学习的 AI 视频课程',
      title: '通过有真实感的场景<br><span class="grad">学习语言。</span>',
      lead: 'LingvoScenes 帮助把允许使用的视频材料变成适合个人学习、教师和创作者的精致语言课程。重点很简单：把语境、讲解和可重复练习放在同一次观看体验中。',
      insight: '学习者不只是背孤立短语。他们会同时看到<strong>意义、情境、语气和讲解</strong>，因此更容易注意并记住真实表达。',
      contactButton: '申请访问',
      overviewButton: '查看概览',
      rolloutNote: 'Windows 桌面应用私密测试中',
      useLabel: '// 使用场景',
      useTitle: '围绕真实语境构建的语言课程',
      uc1Name: '基于场景的课程',
      uc1Desc: '围绕允许使用的学习材料中的有意义时刻，创建紧凑课程。',
      uc1Badge: '核心场景',
      uc2Name: '对话理解',
      uc2Desc: '帮助学习者理解意义如何在一段对话中发展，而不只停留在单句。',
      uc3Name: '清晰讲解',
      uc3Desc: '以适合学习者的方式呈现词汇、语法、语气和文化语境。',
      uc4Name: '创作者可用课程',
      uc4Desc: '为个人学习、课堂或公开学习频道准备精致的教育视频。',
      uc5Name: '学习材料',
      uc5Desc: '用摘要、词汇重点和复习练习来支持课程。',
      uc6Name: '负责任使用',
      uc6Desc: '面向用户有权使用的材料进行教育创作。',
      stepsLabel: '// 学习体验',
      stepsTitle: '学习者从 LingvoScenes 课程中获得什么',
      step1Title: '自然语境',
      step1Desc: '语言出现在能看见情绪和意图的情境中。',
      step2Title: '聚焦学习时刻',
      step2Desc: '课程突出有用表达，但不会让体验像一本词典。',
      step3Title: '简明解释',
      step3Desc: '学习者获得关于意义、语法、语气和用法的简洁说明。',
      step4Title: '观看与重复格式',
      step4Desc: '完成后的课程适合反复观看、课堂使用和自学。',
      step5Title: '可选学习支持',
      step5Desc: '课程可以搭配复习材料、词汇笔记和练习。',
      valueLabel: '// 价值',
      valueTitle: '为教师、创作者和认真学习者而设计',
      value1Title: '有语境的学习',
      value1Text: '场景保留自然速度、情绪和情境，讲解让语言更容易接近。',
      value2Title: '多种学习语言',
      value2Text: '面向学习英语、德语、法语、意大利语、西班牙语、韩语、中文和日语的用户设计。',
      value3Title: '精致的课程结果',
      value3Text: '最终材料的目标是像完成的教育产品，而不是原始片段。',
      value4Title: '负责任发布',
      value4Text: '清晰定位帮助创作者认真考虑教育材料的使用地点和方式。',
      accessLabel: '// 版本和访问',
      accessTitle: '当前私密测试，之后开放更多访问',
      access1Val: 'Trial',
      access1Text: '用于测试流程的受限评估版本',
      access2Val: 'Home',
      access2Text: '用于个人课程制作的桌面版本',
      access3Val: 'Pro',
      access3Text: '计划面向高级创作者和教育者的版本',
      notice: 'LingvoScenes 面向教育用途，并适用于用户有权处理的材料。发布规则和版权要求取决于源材料和平台。'
    }
  }
};

const extraTranslations = {
  de: {
    meta: {
      indexTitle: 'Dojo4Education — KI-Tools für Bildung',
      indexDescription: 'KI-gestützte Mini-Apps und Trainingswerkzeuge für akademische Vorbereitung, mündliche Antworten und Kompetenzaufbau.',
      thesisTitle: 'ThesisAudit — KI-Trainer für mündliche Verteidigungen',
      thesisDescription: 'ThesisAudit hilft Studierenden, mündliche akademische Verteidigungen mit KI-Fragen, Sprachantworten und strukturiertem Feedback zu üben.',
      lingvoTitle: 'LingvoScenes — KI-Sprachlektionen aus echtem Kontext',
      lingvoDescription: 'LingvoScenes hilft, aus erlaubten Materialien ausgearbeitete Sprachvideolektionen mit klaren Erklärungen und Übungsunterstützung zu erstellen.'
    },
    common: {
      products: 'Produkte',
      about: 'Über uns',
      contact: 'Kontakt',
      soon: 'bald',
      thesisAudit: 'ThesisAudit',
      lingvoScenes: 'LingvoScenes',
      lingvaPulse: 'LingvaPulse',
      footer: '© 2026 Dojo4Education · Powered by AI',
      telegram: 'Telegram-Community'
    },
    index: {
      eyebrow: 'KI-Tools für Bildung',
      title: 'Trainieren Sie Fähigkeiten mit <span class="accent">KI-gestützten Lerntrainern</span>',
      subtitle: 'Dojo4Education entwickelt kompakte KI-Mini-Apps, die Lernenden beim Vorbereiten, Erklären, Antworten und Verbessern praktischer akademischer Fähigkeiten helfen.',
      ctaProducts: 'Produkte ansehen',
      ctaThesis: 'ThesisAudit ansehen',
      visualTitle: 'Mini-Apps und Trainingswerkzeuge für Kompetenzaufbau',
      productsLabel: '// produkte',
      productsTitle: 'Fokussierte Werkzeuge statt allgemeiner KI-Chats',
      thesisDesc: 'KI-Trainer für Abschlussverteidigungen und mündliche akademische Vorbereitung. Er erstellt Fragen, nimmt Sprachantworten an, analysiert Argumentation und ist bei Google Play verfügbar.',
      lingvoDesc: 'KI-Desktop-App zum Erstellen ausgearbeiteter Sprachlektionen aus erlaubten Videomaterialien.',
      lingvaDesc: 'KI-Tools für Sprachenlernen: intelligente Übungen, Sprachanalyse und personalisierte Fortschrittsverfolgung.',
      available: 'verfügbar',
      privateRollout: 'privater Rollout',
      aboutLabel: '// unternehmensprofil',
      aboutTitle: 'Kleines Softwareunternehmen mit Fokus auf Bildungstechnologie',
      aboutText: 'Dojo4Education ist ein in Südkorea registriertes Softwareentwicklungsprojekt. Ziel ist es, praktische KI-Tools für Studierende, Lernende und Lehrkräfte zu entwickeln — beginnend mit mündlicher Vorbereitung und Kompetenztraining.',
      businessName: '<strong>Geschäftsname:</strong> Dojo4Education',
      businessNameKr: '<strong>Registrierter koreanischer Name:</strong> 도조포에듀케이션',
      businessType: '<strong>Geschäftsfeld:</strong> Softwareentwicklung',
      businessFocus: '<strong>Fokus:</strong> KI-Tools für Bildung und Kompetenzentwicklung',
      roadmapTitle: 'Roadmap',
      roadmapText: 'Der aktuelle Fokus liegt auf ThesisAudit. LingvaPulse und weitere Lernwerkzeuge sind geplant, wenn die Produktlinie wächst.',
      contactLabel: '// kontakt',
      contactTitle: 'Geschäftsanfragen und Produktupdates',
      contactText: 'Für Geschäftskommunikation, Partnerschaften oder Produktfragen nutzen Sie bitte E-Mail. Community-Updates gibt es über Telegram.',
      emailButton: 'Per E-Mail kontaktieren',
      telegramButton: 'Telegram öffnen'
    },
    thesis: {
      eyebrow: 'KI-Trainer für mündliche Verteidigungen',
      title: 'Etwas zu wissen ist das eine.<br><span class="grad">Es laut zu erklären ist etwas anderes.</span>',
      lead: 'ThesisAudit simuliert eine akademische Verteidigung: Es stellt Fragen zu Ihrem Dokument, nimmt Sprachantworten an und zeigt, wo Ihre Argumentation schwach wird, bevor es vor einer Kommission passiert.',
      insight: 'Ein Text kann beim Lesen klar wirken. Beim lauten Antworten zeigen sich jedoch Lücken in <strong>Logik, Terminologie und Argumentation</strong>. ThesisAudit hilft, sie früh zu finden.',
      download: 'Bei Google Play holen',
      androidNote: 'Android-App bei Google Play verfügbar',
      useLabel: '// anwendungsfälle',
      useTitle: 'Ein Werkzeug für verschiedene mündliche Formate',
      uc1Name: 'Abschlussverteidigung',
      uc1Desc: 'Das Hauptszenario. Fragen zu Thema, Methodik, Schlussfolgerungen und praktischem Nutzen — ähnlich wie in einer echten Kommission.',
      uc1Badge: 'hauptszenario',
      uc2Name: 'Hausarbeit',
      uc2Desc: 'Üben Sie Antworten zum Forschungsthema, zur Struktur, zu Schlussfolgerungen und zur Quellenauswahl.',
      uc3Name: 'Laborbericht',
      uc3Desc: 'Prüfen Sie, ob Sie nicht nur den praktischen Teil, sondern auch die Theorie dahinter erklären können.',
      uc4Name: 'Essay oder Referat',
      uc4Desc: 'Üben Sie Themenerklärung, Argumentation und Antworten auf Nachfragen einer Lehrkraft.',
      uc5Name: 'Seminare',
      uc5Desc: 'Testen Sie Ihre Bereitschaft, Kursthemen zu diskutieren und mit klaren Argumenten teilzunehmen.',
      uc6Name: 'Prüfungen und mündliche Tests',
      uc6Desc: 'Modellieren Sie Fragen aus Lernmaterialien und trainieren Sie mündliche Antworten unter realistischem Druck.',
      stepsLabel: '// so funktioniert es',
      stepsTitle: 'Eine strukturierte Generalprobe, nicht nur zufällige Fragen',
      step1Title: 'Material hochladen',
      step1Desc: 'Abschlussarbeit, Hausarbeit, Bericht, Vorlesungsnotizen oder Lehrbuchkapitel — jedes Vorbereitungsdokument im .docx-Format.',
      step2Title: 'Fragen erhalten',
      step2Desc: 'Die KI analysiert das Material und erstellt Fragen zu Thema, Methodik, Schlussfolgerungen, praktischem Wert und Schlüsselbegriffen.',
      step3Title: 'Mit Stimme antworten',
      step3Desc: 'Antworten Sie laut wie in einer echten Verteidigung. Sprachantworten werden transkribiert und analysiert.',
      step4Title: 'Nachfragen',
      step4Desc: 'Auf Basis Ihrer Antworten stellt das System weitere Fragen, um Verständnis und Argumentationslogik zu prüfen.',
      step5Title: 'Abschlussbericht erhalten',
      step5Desc: 'Ein detaillierter Bericht mit Bereitschaftsniveau, Stärken, Schwächen und konkreten Bereichen zur Verbesserung vor der echten Verteidigung.',
      valueLabel: '// nutzen',
      valueTitle: 'Ein sicherer Raum für echte Übung',
      value1Title: 'Schwachstellen früh finden',
      value1Text: 'Erkennen Sie Verständnislücken vor dem echten Gespräch mit Lehrkraft oder Kommission.',
      value2Title: 'Mündliche Antworten trainieren',
      value2Text: 'Üben Sie lautes Erklären — eine andere Fähigkeit als reines Wissen.',
      value3Title: 'Argumentation aufbauen',
      value3Text: 'Verbessern Sie Erklärungslogik, Verbindung von Theorie und Praxis sowie Begründung Ihrer Schlussfolgerungen.',
      value4Title: 'Stress reduzieren',
      value4Text: 'Wenn Sie eine ähnliche Situation bereits geübt haben, wirkt die echte Verteidigung weniger unbekannt.',
      creditsLabel: '// credits und zugang',
      creditsTitle: 'Kostenlos starten',
      credit1Val: '20',
      credit1Text: 'kostenlose Dojocoins nach Autorisierung',
      credit2Val: '1.000',
      credit2Text: 'Wörter pro 1 Dojocoin, aufgerundet',
      credit3Val: 'Google Play',
      credit3Text: 'Vertriebskanal der Android-App',
      notice: 'Dojocoins messen den Umfang der Dokumentverarbeitung. Der aktuelle kostenlose Start gibt 20 Dojocoins, und 1 Dojocoin deckt 1.000 Wörter mit Aufrundung ab.'
    },
    lingvo: {
      eyebrow: 'KI-Videolektionen für Sprachenlernen',
      title: 'Sprachen lernen mit<br><span class="grad">Szenen, die sich echt anfühlen.</span>',
      lead: 'LingvoScenes hilft, erlaubte Videomaterialien in ausgearbeitete Sprachlektionen für Selbststudium, Lehrkräfte und Creator zu verwandeln. Im Mittelpunkt stehen Kontext, Erklärung und wiederholbare Übung in einer Seherfahrung.',
      insight: 'Lernende merken sich nicht nur isolierte Sätze. Sie sehen <strong>Bedeutung, Situation, Ton und Erklärung</strong> zusammen, sodass echte Sprache leichter auffällt und im Gedächtnis bleibt.',
      contactButton: 'Zugang anfragen',
      overviewButton: 'Überblick ansehen',
      rolloutNote: 'Windows-Desktop-App im privaten Rollout',
      useLabel: '// anwendungsfälle',
      useTitle: 'Sprachlektionen rund um echten Kontext',
      uc1Name: 'Szenenbasierte Lektionen',
      uc1Desc: 'Erstellen Sie kompakte Lektionen rund um bedeutungsvolle Momente aus erlaubten Lernmaterialien.',
      uc1Badge: 'hauptszenario',
      uc2Name: 'Dialogverständnis',
      uc2Desc: 'Hilft Lernenden zu verfolgen, wie sich Bedeutung in einem Gespräch entwickelt, nicht nur in einem einzelnen Satz.',
      uc3Name: 'Klare Erklärungen',
      uc3Desc: 'Stellt Wortschatz, Grammatik, Ton und kulturellen Kontext lernfreundlich dar.',
      uc4Name: 'Creator-fertige Lektionen',
      uc4Desc: 'Bereitet ausgearbeitete Bildungsvideos für Selbststudium, Unterricht oder öffentliche Lernkanäle vor.',
      uc5Name: 'Lernmaterialien',
      uc5Desc: 'Ergänzt Lektionen mit Zusammenfassungen, Wortschatzfokus und Übungen zur Wiederholung.',
      uc6Name: 'Verantwortungsvolle Nutzung',
      uc6Desc: 'Für Bildungsarbeit mit Materialien gedacht, zu deren Nutzung der Anwender berechtigt ist.',
      stepsLabel: '// lernerlebnis',
      stepsTitle: 'Was Lernende aus einer LingvoScenes-Lektion mitnehmen',
      step1Title: 'Natürlicher Kontext',
      step1Desc: 'Sprache erscheint in einer Situation, in der Emotion und Absicht sichtbar sind.',
      step2Title: 'Fokussierte Lernmomente',
      step2Desc: 'Lektionen heben nützliche Ausdrücke hervor, ohne sich wie ein Wörterbuch anzufühlen.',
      step3Title: 'Einfache Erklärungen',
      step3Desc: 'Lernende erhalten kurze Erklärungen zu Bedeutung, Grammatik, Ton und Verwendung.',
      step4Title: 'Format zum Wiederholen',
      step4Desc: 'Die fertige Lektion eignet sich zum erneuten Ansehen, für Unterricht und Selbststudium.',
      step5Title: 'Optionale Lernunterstützung',
      step5Desc: 'Lektionen können mit Wiederholungsmaterial, Wortschatznotizen und Übungen kombiniert werden.',
      valueLabel: '// wert',
      valueTitle: 'Für Lehrkräfte, Creator und ernsthafte Lernende',
      value1Title: 'Kontextreiches Lernen',
      value1Text: 'Szenen behalten natürliches Tempo, Emotion und Situation, während Erklärungen die Sprache zugänglicher machen.',
      value2Title: 'Mehrere Lernsprachen',
      value2Text: 'Für Lernende mit Englisch, Deutsch, Französisch, Italienisch, Spanisch, Koreanisch, Chinesisch und Japanisch gedacht.',
      value3Title: 'Ausgearbeitetes Lernergebnis',
      value3Text: 'Das finale Material soll wie ein fertiges Bildungsprodukt wirken, nicht wie ein Rohclip.',
      value4Title: 'Verantwortungsvolles Veröffentlichen',
      value4Text: 'Eine klare Positionierung hilft Creatorn, sorgfältig über Ort und Art der Nutzung von Lernmaterialien nachzudenken.',
      accessLabel: '// editionen und zugang',
      accessTitle: 'Jetzt privater Rollout, später breiterer Zugang',
      access1Val: 'Trial',
      access1Text: 'begrenzter Testzugang zum Kennenlernen des Produkts',
      access2Val: 'Home',
      access2Text: 'Desktop-Edition für persönliche Lektionserstellung',
      access3Val: 'Pro',
      access3Text: 'geplante Edition für fortgeschrittene Creator und Lehrkräfte',
      notice: 'LingvoScenes ist für Bildungszwecke mit Materialien gedacht, die Nutzer verarbeiten dürfen. Veröffentlichungsregeln und Urheberrechtsanforderungen hängen vom Ausgangsmaterial und der Plattform ab.'
    }
  },
  fr: {
    meta: {
      indexTitle: 'Dojo4Education — outils IA pour l’éducation',
      indexDescription: 'Mini-apps et outils d’entraînement avec IA pour la préparation académique, les réponses orales et le développement des compétences.',
      thesisTitle: 'ThesisAudit — entraîneur IA pour soutenances orales',
      thesisDescription: 'ThesisAudit aide les étudiants à répéter une soutenance avec des questions IA, des réponses vocales et un retour structuré.',
      lingvoTitle: 'LingvoScenes — leçons IA à partir de contextes réels',
      lingvoDescription: 'LingvoScenes aide à créer des leçons vidéo de langue soignées à partir de contenus autorisés, avec explications claires et support de pratique.'
    },
    common: {
      products: 'Produits',
      about: 'À propos',
      contact: 'Contact',
      soon: 'bientôt',
      thesisAudit: 'ThesisAudit',
      lingvoScenes: 'LingvoScenes',
      lingvaPulse: 'LingvaPulse',
      footer: '© 2026 Dojo4Education · Powered by AI',
      telegram: 'Communauté Telegram'
    },
    index: {
      eyebrow: 'Outils IA pour l’éducation',
      title: 'Entraînez vos compétences avec des <span class="accent">outils IA ciblés</span>',
      subtitle: 'Dojo4Education crée des mini-apps IA compactes qui aident à préparer, expliquer, répondre et améliorer des compétences académiques pratiques.',
      ctaProducts: 'Explorer les produits',
      ctaThesis: 'Voir ThesisAudit',
      visualTitle: 'Mini-apps et outils d’entraînement pour progresser',
      productsLabel: '// produits',
      productsTitle: 'Des outils ciblés plutôt que des chats IA génériques',
      thesisDesc: 'Entraîneur IA pour soutenance et préparation orale académique. Il génère des questions, accepte les réponses vocales, analyse le raisonnement et est disponible sur Google Play.',
      lingvoDesc: 'Application desktop IA pour créer des leçons de langue soignées à partir de contenus vidéo autorisés.',
      lingvaDesc: 'Outils IA pour apprendre les langues : exercices intelligents, analyse de la parole et suivi personnalisé.',
      available: 'disponible',
      privateRollout: 'accès privé',
      aboutLabel: '// profil',
      aboutTitle: 'Petite entreprise logicielle orientée EdTech',
      aboutText: 'Dojo4Education est un projet de développement logiciel enregistré en Corée du Sud. Son objectif est de créer des outils IA pratiques pour les étudiants, les apprenants et les enseignants, en commençant par la préparation orale.',
      businessName: '<strong>Nom commercial :</strong> Dojo4Education',
      businessNameKr: '<strong>Nom coréen enregistré :</strong> 도조포에듀케이션',
      businessType: '<strong>Activité :</strong> développement logiciel',
      businessFocus: '<strong>Focus :</strong> outils IA pour l’éducation et les compétences',
      roadmapTitle: 'Feuille de route',
      roadmapText: 'Le focus actuel est ThesisAudit. LingvaPulse et d’autres outils d’apprentissage sont prévus avec l’expansion de la gamme.',
      contactLabel: '// contact',
      contactTitle: 'Demandes professionnelles et actualités produit',
      contactText: 'Pour les échanges professionnels, partenariats ou questions produit, utilisez l’e-mail. Les mises à jour de la communauté sont disponibles sur Telegram.',
      emailButton: 'Contacter par e-mail',
      telegramButton: 'Ouvrir Telegram'
    },
    thesis: {
      eyebrow: 'Entraîneur IA pour soutenances orales',
      title: 'Savoir est une chose.<br><span class="grad">L’expliquer à voix haute en est une autre.</span>',
      lead: 'ThesisAudit simule une soutenance académique : il pose des questions sur votre document, accepte des réponses vocales et montre où votre raisonnement devient fragile avant le vrai jury.',
      insight: 'Un texte peut sembler clair à la lecture. Mais à l’oral, des lacunes apparaissent dans <strong>la logique, la terminologie et l’argumentation</strong>. ThesisAudit aide à les repérer tôt.',
      download: 'Disponible sur Google Play',
      androidNote: 'Application Android disponible sur Google Play',
      useLabel: '// cas d’usage',
      useTitle: 'Un outil pour plusieurs formats oraux',
      uc1Name: 'Soutenance',
      uc1Desc: 'Le scénario principal. Questions sur le sujet, la méthodologie, les conclusions et la valeur pratique — comme devant un vrai jury.',
      uc1Badge: 'scénario principal',
      uc2Name: 'Mémoire ou dossier',
      uc2Desc: 'Entraînez les réponses sur le sujet, la structure, les conclusions et le choix des sources.',
      uc3Name: 'Compte rendu de laboratoire',
      uc3Desc: 'Vérifiez que vous pouvez expliquer la partie pratique et la théorie qui la soutient.',
      uc4Name: 'Essai ou exposé',
      uc4Desc: 'Répétez l’explication du sujet, l’argumentation et les réponses aux questions de suivi.',
      uc5Name: 'Séminaires',
      uc5Desc: 'Testez votre capacité à discuter les thèmes du cours avec des arguments clairs.',
      uc6Name: 'Examens oraux',
      uc6Desc: 'Modélisez des questions à partir des supports et entraînez des réponses orales sous pression réaliste.',
      stepsLabel: '// fonctionnement',
      stepsTitle: 'Une répétition structurée, pas une simple liste de questions',
      step1Title: 'Téléversez votre document',
      step1Desc: 'Mémoire, dossier, rapport, notes de cours ou chapitres de manuel — tout document de préparation au format .docx.',
      step2Title: 'Recevez des questions',
      step2Desc: 'L’IA analyse le document et génère des questions sur le sujet, la méthode, les conclusions, la valeur pratique et les notions clés.',
      step3Title: 'Répondez à voix haute',
      step3Desc: 'Répondez comme lors d’une vraie soutenance. Les réponses vocales sont transcrites et analysées.',
      step4Title: 'Questions de suivi',
      step4Desc: 'À partir de vos réponses, le système pose des questions supplémentaires pour tester la profondeur et la logique.',
      step5Title: 'Recevez un rapport final',
      step5Desc: 'Un rapport détaillé avec niveau de préparation, points forts, points faibles et axes de progrès avant la vraie soutenance.',
      valueLabel: '// valeur',
      valueTitle: 'Un espace sûr pour une vraie répétition',
      value1Title: 'Repérer les faiblesses tôt',
      value1Text: 'Détectez les lacunes de compréhension avant la conversation réelle avec un enseignant ou un jury.',
      value2Title: 'Travailler l’oral',
      value2Text: 'Apprenez à expliquer à voix haute — une compétence différente du simple fait de connaître.',
      value3Title: 'Construire l’argumentation',
      value3Text: 'Améliorez la logique, le lien entre théorie et pratique et la justification des conclusions.',
      value4Title: 'Réduire le stress',
      value4Text: 'Quand une situation similaire a déjà été répétée, la vraie soutenance paraît moins inconnue.',
      creditsLabel: '// crédits et accès',
      creditsTitle: 'Commencer gratuitement',
      credit1Val: '20',
      credit1Text: 'Dojocoins gratuits après autorisation',
      credit2Val: '1 000',
      credit2Text: 'mots par 1 Dojocoin, arrondis au supérieur',
      credit3Val: 'Google Play',
      credit3Text: 'canal de distribution Android',
      notice: 'Les Dojocoins mesurent le volume de traitement des documents. Le démarrage gratuit actuel donne 20 Dojocoins, et 1 Dojocoin couvre 1 000 mots avec arrondi.'
    },
    lingvo: {
      eyebrow: 'Leçons vidéo IA pour apprendre les langues',
      title: 'Apprenez les langues avec<br><span class="grad">des scènes qui semblent réelles.</span>',
      lead: 'LingvoScenes aide à transformer des contenus vidéo autorisés en leçons de langue soignées pour l’étude personnelle, les enseignants et les créateurs. L’objectif est simple : contexte, explication et pratique répétable dans une même expérience.',
      insight: 'Les apprenants ne mémorisent pas seulement des phrases isolées. Ils voient <strong>le sens, la situation, le ton et l’explication</strong> ensemble, ce qui rend la langue réelle plus facile à remarquer et à retenir.',
      contactButton: 'Demander l’accès',
      overviewButton: 'Voir l’aperçu',
      rolloutNote: 'Application Windows en accès privé',
      useLabel: '// cas d’usage',
      useTitle: 'Des leçons de langue construites autour du contexte réel',
      uc1Name: 'Leçons basées sur des scènes',
      uc1Desc: 'Créez des leçons compactes autour de moments significatifs issus de contenus d’apprentissage autorisés.',
      uc1Badge: 'scénario principal',
      uc2Name: 'Compréhension du dialogue',
      uc2Desc: 'Aidez les apprenants à suivre l’évolution du sens dans une conversation, pas seulement dans une phrase.',
      uc3Name: 'Explications claires',
      uc3Desc: 'Présentez vocabulaire, grammaire, ton et contexte culturel de manière accessible.',
      uc4Name: 'Leçons prêtes pour créateurs',
      uc4Desc: 'Préparez des vidéos éducatives soignées pour l’étude privée, les cours ou les chaînes d’apprentissage.',
      uc5Name: 'Supports d’étude',
      uc5Desc: 'Complétez les leçons avec résumés, vocabulaire ciblé et exercices de révision.',
      uc6Name: 'Usage responsable',
      uc6Desc: 'Conçu pour un travail éducatif avec des contenus que l’utilisateur est autorisé à utiliser.',
      stepsLabel: '// expérience d’apprentissage',
      stepsTitle: 'Ce qu’un apprenant reçoit dans une leçon LingvoScenes',
      step1Title: 'Contexte naturel',
      step1Desc: 'La langue apparaît dans une situation où l’émotion et l’intention sont visibles.',
      step2Title: 'Moments d’apprentissage ciblés',
      step2Desc: 'Les leçons mettent en valeur des expressions utiles sans donner l’impression d’un dictionnaire.',
      step3Title: 'Explications simples',
      step3Desc: 'Les apprenants reçoivent des explications concises du sens, de la grammaire, du ton et de l’usage.',
      step4Title: 'Format à revoir',
      step4Desc: 'La leçon finie est pensée pour être revue, utilisée en classe ou étudiée seul.',
      step5Title: 'Support d’étude optionnel',
      step5Desc: 'Les leçons peuvent être accompagnées de supports de révision, notes de vocabulaire et exercices.',
      valueLabel: '// valeur',
      valueTitle: 'Conçu pour enseignants, créateurs et apprenants sérieux',
      value1Title: 'Apprentissage avec contexte',
      value1Text: 'Les scènes gardent vitesse naturelle, émotion et situation, tandis que les explications rendent la langue accessible.',
      value2Title: 'Plusieurs langues d’apprentissage',
      value2Text: 'Conçu pour les apprenants travaillant l’anglais, l’allemand, le français, l’italien, l’espagnol, le coréen, le chinois et le japonais.',
      value3Title: 'Résultat pédagogique soigné',
      value3Text: 'Le résultat final est pensé comme un produit éducatif terminé, pas comme un extrait brut.',
      value4Title: 'Publication responsable',
      value4Text: 'Un positionnement clair aide les créateurs à réfléchir soigneusement au lieu et à la manière d’utiliser les contenus éducatifs.',
      accessLabel: '// éditions et accès',
      accessTitle: 'Accès privé maintenant, ouverture plus large ensuite',
      access1Val: 'Trial',
      access1Text: 'accès d’évaluation limité pour découvrir le produit',
      access2Val: 'Home',
      access2Text: 'édition desktop pour créer des leçons personnelles',
      access3Val: 'Pro',
      access3Text: 'édition prévue pour créateurs avancés et enseignants',
      notice: 'LingvoScenes est conçu pour un usage éducatif avec des contenus que l’utilisateur est autorisé à traiter. Les règles de publication et de droit d’auteur dépendent du contenu source et de la plateforme.'
    }
  },
  es: {
    meta: {
      indexTitle: 'Dojo4Education — herramientas de IA para educación',
      indexDescription: 'Miniaplicaciones y entrenadores con IA para preparación académica, respuestas orales y desarrollo de habilidades.',
      thesisTitle: 'ThesisAudit — entrenador de IA para defensas orales',
      thesisDescription: 'ThesisAudit ayuda a practicar defensas académicas con preguntas de IA, respuestas de voz y retroalimentación estructurada.',
      lingvoTitle: 'LingvoScenes — lecciones de IA desde contexto real',
      lingvoDescription: 'LingvoScenes ayuda a crear videolecciones de idioma pulidas a partir de materiales permitidos, con explicaciones claras y apoyo para la práctica.'
    },
    common: {
      products: 'Productos',
      about: 'Acerca de',
      contact: 'Contacto',
      soon: 'pronto',
      thesisAudit: 'ThesisAudit',
      lingvoScenes: 'LingvoScenes',
      lingvaPulse: 'LingvaPulse',
      footer: '© 2026 Dojo4Education · Powered by AI',
      telegram: 'Comunidad en Telegram'
    },
    index: {
      eyebrow: 'Herramientas de IA para educación',
      title: 'Practica habilidades con <span class="accent">entrenadores impulsados por IA</span>',
      subtitle: 'Dojo4Education desarrolla miniaplicaciones de IA que ayudan a preparar, explicar, responder y mejorar habilidades académicas prácticas.',
      ctaProducts: 'Explorar productos',
      ctaThesis: 'Ver ThesisAudit',
      visualTitle: 'Miniaplicaciones y entrenadores para desarrollar habilidades',
      productsLabel: '// productos',
      productsTitle: 'Herramientas enfocadas en lugar de chats genéricos de IA',
      thesisDesc: 'Entrenador de IA para defensa de tesis y preparación oral académica. Genera preguntas, acepta respuestas de voz, analiza el razonamiento y está disponible en Google Play.',
      lingvoDesc: 'Aplicación de escritorio con IA para crear lecciones de idioma pulidas a partir de materiales de video permitidos.',
      lingvaDesc: 'Herramientas de IA para aprender idiomas: ejercicios inteligentes, análisis del habla y progreso personalizado.',
      available: 'disponible',
      privateRollout: 'acceso privado',
      aboutLabel: '// perfil',
      aboutTitle: 'Pequeña empresa de software enfocada en tecnología educativa',
      aboutText: 'Dojo4Education es un proyecto de desarrollo de software registrado en Corea del Sur. Su objetivo es crear herramientas prácticas de IA para estudiantes, aprendices y docentes, empezando por la preparación oral.',
      businessName: '<strong>Nombre comercial:</strong> Dojo4Education',
      businessNameKr: '<strong>Nombre coreano registrado:</strong> 도조포에듀케이션',
      businessType: '<strong>Actividad:</strong> desarrollo de software',
      businessFocus: '<strong>Enfoque:</strong> herramientas de IA para educación y habilidades',
      roadmapTitle: 'Hoja de ruta',
      roadmapText: 'El foco actual es ThesisAudit. LingvaPulse y otras herramientas de aprendizaje están previstas a medida que crezca la línea de productos.',
      contactLabel: '// contacto',
      contactTitle: 'Consultas comerciales y novedades del producto',
      contactText: 'Para comunicación comercial, alianzas o preguntas sobre productos, usa el correo electrónico. Las novedades de la comunidad están en Telegram.',
      emailButton: 'Contactar por correo',
      telegramButton: 'Abrir Telegram'
    },
    thesis: {
      eyebrow: 'Entrenador de IA para defensa oral',
      title: 'Saber es una cosa.<br><span class="grad">Explicarlo en voz alta es otra.</span>',
      lead: 'ThesisAudit simula una defensa académica: hace preguntas basadas en tu documento, acepta respuestas de voz y muestra dónde se debilita tu razonamiento antes de estar frente a un comité.',
      insight: 'Un texto puede parecer claro al leerlo. Pero al responder en voz alta aparecen lagunas en <strong>lógica, terminología y argumentación</strong>. ThesisAudit ayuda a encontrarlas pronto.',
      download: 'Obtener en Google Play',
      androidNote: 'Aplicación Android disponible en Google Play',
      useLabel: '// casos de uso',
      useTitle: 'Una herramienta para varios formatos orales',
      uc1Name: 'Defensa de tesis',
      uc1Desc: 'El escenario principal. Preguntas sobre tema, metodología, conclusiones y valor práctico, similares a un comité real.',
      uc1Badge: 'escenario principal',
      uc2Name: 'Trabajo de curso',
      uc2Desc: 'Practica respuestas sobre el tema, la estructura, las conclusiones y la selección de fuentes.',
      uc3Name: 'Informe de laboratorio',
      uc3Desc: 'Comprueba si puedes explicar no solo la parte práctica, sino también la teoría detrás de ella.',
      uc4Name: 'Ensayo o exposición',
      uc4Desc: 'Ensaya la explicación del tema, la argumentación y las respuestas a preguntas de seguimiento.',
      uc5Name: 'Seminarios',
      uc5Desc: 'Evalúa tu preparación para discutir temas de clase y participar con argumentos claros.',
      uc6Name: 'Exámenes orales',
      uc6Desc: 'Modela preguntas a partir de materiales de estudio y entrena respuestas orales bajo presión realista.',
      stepsLabel: '// cómo funciona',
      stepsTitle: 'Un ensayo estructurado, no solo preguntas aleatorias',
      step1Title: 'Sube tu material',
      step1Desc: 'Tesis, trabajo, informe, apuntes o capítulos de libro: cualquier documento de preparación en formato .docx.',
      step2Title: 'Recibe preguntas',
      step2Desc: 'La IA analiza el material y genera preguntas sobre tema, metodología, conclusiones, valor práctico y términos clave.',
      step3Title: 'Responde con voz',
      step3Desc: 'Responde en voz alta como en una defensa real. Las respuestas se transcriben y analizan.',
      step4Title: 'Preguntas de seguimiento',
      step4Desc: 'Según tus respuestas, el sistema hace preguntas adicionales para comprobar profundidad y lógica argumentativa.',
      step5Title: 'Recibe el informe final',
      step5Desc: 'Un informe detallado con nivel de preparación, fortalezas, puntos débiles y áreas concretas para mejorar.',
      valueLabel: '// valor',
      valueTitle: 'Un espacio seguro para practicar de verdad',
      value1Title: 'Encuentra debilidades antes',
      value1Text: 'Detecta lagunas de comprensión antes de la conversación real con docente o comité.',
      value2Title: 'Entrena respuestas orales',
      value2Text: 'Practica explicar en voz alta: una habilidad distinta a simplemente conocer el material.',
      value3Title: 'Construye argumentación',
      value3Text: 'Mejora la lógica de explicación, la conexión entre teoría y práctica y la justificación de conclusiones.',
      value4Title: 'Reduce el estrés',
      value4Text: 'Cuando ya has practicado una situación similar, la defensa real se siente menos desconocida.',
      creditsLabel: '// créditos y acceso',
      creditsTitle: 'Empieza gratis',
      credit1Val: '20',
      credit1Text: 'Dojocoins gratis tras autorización',
      credit2Val: '1.000',
      credit2Text: 'palabras por 1 Dojocoin, redondeado hacia arriba',
      credit3Val: 'Google Play',
      credit3Text: 'canal de distribución Android',
      notice: 'Los Dojocoins miden el volumen de procesamiento de documentos. El inicio gratuito actual ofrece 20 Dojocoins, y 1 Dojocoin cubre 1.000 palabras con redondeo.'
    },
    lingvo: {
      eyebrow: 'Videolecciones de IA para aprender idiomas',
      title: 'Aprende idiomas con<br><span class="grad">escenas que se sienten reales.</span>',
      lead: 'LingvoScenes ayuda a convertir materiales de video permitidos en lecciones de idioma pulidas para estudio personal, docentes y creadores. El foco es simple: contexto, explicación y práctica repetible en una sola experiencia.',
      insight: 'Los estudiantes no solo memorizan frases aisladas. Ven <strong>significado, situación, tono y explicación</strong> juntos, para notar y recordar mejor el habla real.',
      contactButton: 'Solicitar acceso',
      overviewButton: 'Ver resumen',
      rolloutNote: 'Aplicación Windows en acceso privado',
      useLabel: '// casos de uso',
      useTitle: 'Lecciones de idioma construidas alrededor de contexto real',
      uc1Name: 'Lecciones basadas en escenas',
      uc1Desc: 'Crea lecciones compactas alrededor de momentos significativos de materiales de aprendizaje permitidos.',
      uc1Badge: 'escenario principal',
      uc2Name: 'Comprensión del diálogo',
      uc2Desc: 'Ayuda a seguir cómo se desarrolla el significado en una conversación, no solo en una frase.',
      uc3Name: 'Explicaciones claras',
      uc3Desc: 'Presenta vocabulario, gramática, tono y contexto cultural de forma amigable para el estudiante.',
      uc4Name: 'Lecciones listas para creadores',
      uc4Desc: 'Prepara videos educativos pulidos para estudio privado, clases o canales públicos de aprendizaje.',
      uc5Name: 'Materiales de estudio',
      uc5Desc: 'Apoya las lecciones con resúmenes, vocabulario enfocado y ejercicios de repaso.',
      uc6Name: 'Uso responsable',
      uc6Desc: 'Diseñado para trabajo educativo con materiales que el usuario tiene derecho a usar.',
      stepsLabel: '// experiencia de aprendizaje',
      stepsTitle: 'Qué recibe el estudiante en una lección LingvoScenes',
      step1Title: 'Contexto natural',
      step1Desc: 'El idioma aparece dentro de una situación, con emoción e intención visibles.',
      step2Title: 'Momentos de aprendizaje enfocados',
      step2Desc: 'Las lecciones resaltan expresiones útiles sin sentirse como un diccionario.',
      step3Title: 'Explicaciones simples',
      step3Desc: 'El estudiante recibe explicaciones concisas de significado, gramática, tono y uso.',
      step4Title: 'Formato para ver y repetir',
      step4Desc: 'La lección terminada sirve para verla varias veces, usarla en clase o estudiar solo.',
      step5Title: 'Apoyo de estudio opcional',
      step5Desc: 'Las lecciones pueden acompañarse con materiales de repaso, notas de vocabulario y ejercicios.',
      valueLabel: '// valor',
      valueTitle: 'Para docentes, creadores y estudiantes serios',
      value1Title: 'Aprendizaje con contexto',
      value1Text: 'Las escenas conservan velocidad natural, emoción y situación, mientras las explicaciones hacen el idioma accesible.',
      value2Title: 'Varios idiomas de aprendizaje',
      value2Text: 'Diseñado para estudiantes que trabajan con inglés, alemán, francés, italiano, español, coreano, chino y japonés.',
      value3Title: 'Resultado educativo pulido',
      value3Text: 'El material final está pensado para sentirse como un producto educativo terminado, no como un clip sin preparar.',
      value4Title: 'Publicación responsable',
      value4Text: 'Un posicionamiento claro ayuda a los creadores a pensar con cuidado dónde y cómo usan los materiales educativos.',
      accessLabel: '// ediciones y acceso',
      accessTitle: 'Acceso privado ahora, apertura más amplia después',
      access1Val: 'Trial',
      access1Text: 'acceso de evaluación limitado para probar el producto',
      access2Val: 'Home',
      access2Text: 'edición de escritorio para crear lecciones personales',
      access3Val: 'Pro',
      access3Text: 'edición prevista para creadores avanzados y docentes',
      notice: 'LingvoScenes está diseñado para uso educativo con materiales que el usuario tiene permiso para procesar. Las reglas de publicación y derechos de autor dependen del material y la plataforma.'
    }
  }
};

function mergeTranslations(base, override) {
  const result = { ...base };
  Object.entries(override).forEach(([key, value]) => {
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      result[key] = mergeTranslations(base[key] || {}, value);
    } else {
      result[key] = value;
    }
  });
  return result;
}

Object.entries(extraTranslations).forEach(([lang, pack]) => {
  t[lang] = mergeTranslations(t.en, pack);
});

function getNested(obj, path) {
  return path.split('.').reduce((acc, part) => acc && acc[part], obj);
}

function normalizeLang(value) {
  if (!value) return DEFAULT_LANG;
  const short = String(value).slice(0, 2).toLowerCase();
  return SUPPORTED_LANGS.includes(short) ? short : DEFAULT_LANG;
}

function getInitialLang() {
  const url = new URL(window.location.href);
  const fromQuery = url.searchParams.get('lang');
  if (fromQuery) return normalizeLang(fromQuery);
  const saved = localStorage.getItem(STORAGE_KEY);
  if (saved) return normalizeLang(saved);
  const browserLang = navigator.languages && navigator.languages.length ? navigator.languages[0] : navigator.language;
  if (browserLang) return normalizeLang(browserLang);
  return DEFAULT_LANG;
}

function updateMeta(lang, page) {
  const langPack = t[lang] || t[DEFAULT_LANG];
  const titleMap = {
    thesis: 'thesisTitle',
    lingvo: 'lingvoTitle'
  };
  const descMap = {
    thesis: 'thesisDescription',
    lingvo: 'lingvoDescription'
  };
  const titleKey = titleMap[page] || 'indexTitle';
  const descKey = descMap[page] || 'indexDescription';
  document.title = langPack.meta[titleKey];
  const description = langPack.meta[descKey];
  const metaDescription = document.querySelector('meta[name="description"]');
  if (metaDescription) metaDescription.setAttribute('content', description);
  const ogTitle = document.querySelector('meta[property="og:title"]');
  const ogDescription = document.querySelector('meta[property="og:description"]');
  if (ogTitle) ogTitle.setAttribute('content', langPack.meta[titleKey]);
  if (ogDescription) ogDescription.setAttribute('content', description);
}

function decorateInternalLinks(lang) {
  document.querySelectorAll('a[href]').forEach((link) => {
    const raw = link.getAttribute('href');
    if (!raw || raw.startsWith('http') || raw.startsWith('mailto:') || raw.startsWith('tel:') || raw.startsWith('#')) return;
    const [pathPart, hashPart] = raw.split('#');
    const [base, queryPart = ''] = pathPart.split('?');
    if (!base.endsWith('.html')) return;
    const params = new URLSearchParams(queryPart);
    params.set('lang', lang);
    link.setAttribute('href', `${base}?${params.toString()}${hashPart ? `#${hashPart}` : ''}`);
  });
}

function populateLanguageSelector(selector, selectedLang) {
  const currentOptions = Array.from(selector.options).map((option) => option.value).join(',');
  const expectedOptions = LANGUAGE_OPTIONS.map((option) => option.code).join(',');
  if (currentOptions !== expectedOptions) {
    selector.innerHTML = '';
    LANGUAGE_OPTIONS.forEach(({ code, label }) => {
      const option = document.createElement('option');
      option.value = code;
      option.textContent = label;
      selector.appendChild(option);
    });
  }
  selector.value = selectedLang;
}

function applyLanguage(lang) {
  const safeLang = normalizeLang(lang);
  const page = document.body.dataset.page || 'index';
  const langPack = t[safeLang] || t[DEFAULT_LANG];
  document.documentElement.lang = safeLang;

  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const value = getNested(langPack, el.dataset.i18n);
    if (typeof value === 'string') el.textContent = value;
  });

  document.querySelectorAll('[data-i18n-html]').forEach((el) => {
    const value = getNested(langPack, el.dataset.i18nHtml);
    if (typeof value === 'string') el.innerHTML = value;
  });

  document.querySelectorAll('[data-i18n-aria]').forEach((el) => {
    const value = getNested(langPack, el.dataset.i18nAria);
    if (typeof value === 'string') el.setAttribute('aria-label', value);
  });

  updateMeta(safeLang, page);
  decorateInternalLinks(safeLang);
  localStorage.setItem(STORAGE_KEY, safeLang);

  const url = new URL(window.location.href);
  url.searchParams.set('lang', safeLang);
  window.history.replaceState({}, '', url.toString());

  const selector = document.querySelector('#lang-select');
  if (selector) populateLanguageSelector(selector, safeLang);
}

document.addEventListener('DOMContentLoaded', () => {
  const lang = getInitialLang();
  applyLanguage(lang);
  const selector = document.querySelector('#lang-select');
  if (selector) {
    selector.addEventListener('change', (event) => applyLanguage(event.target.value));
  }
});
